///////////////////////////////////////////////////////////////////////////////
// $Revision: 50162 $
///////////////////////////////////////////////////////////////////////////////

#ifndef RC_SH
#define RC_SH

///////////////////////////////////////////////////////////////////////////////
// FIO
///////////////////////////////////////////////////////////////////////////////

#define FILE_NOT_FOUND_RC -2
#define PATH_NOT_FOUND_RC -3
#define TOO_MANY_OPEN_FILES_RC -4
#define ACCESS_DENIED_RC -5
#define MEMORY_CONTROL_BLOCKS_RC -7
#define INSUFFICIENT_MEMORY_RC -8
#define FILE_TOO_LARGE_RC -9
#define INVALID_DRIVE_RC -15
#define NO_MORE_FILES_RC -18
#define DISK_IS_WRITE_PROTECTED_RC -19
#define UNKNOWN_UNIT_RC -20
#define DRIVE_NOT_READY_RC -21
#define BAD_DEVICE_COMMAND_RC -22
#define DATA_ERROR_RC -23
#define BAD_REQUEST_STRUCTURE_LENGTH_RC -24
#define SEEK_ERROR_RC -25
#define UNKNOWN_MEDIA_TYPE_RC -26
#define SECTOR_NOT_FOUND_RC -27
#define PRINTER_OUT_OF_PAPER_RC -28
#define WRITE_FAULT_RC -29
#define READ_FAULT_RC -30
#define GENERAL_FAILURE_RC -31
#define ERROR_OPENING_FILE_RC -32
#define ERROR_READING_FILE_RC -33
#define ERROR_WRITING_FILE_RC -34
#define ERROR_CLOSING_FILE_RC -35
#define INSUFFICIENT_DISK_SPACE_RC -36
#define PROGRAM_CAN_NOT_BE_RUN_IN_OS2_RC -37
#define ERROR_CREATING_DIRECTORY_RC -38
#define SESSION_PARENT_EXISTS_RC -39
#define PIF_FILE_NOT_FOUND_RC -40
#define BAD_PIF_FILE_RC -41
#define UNABLE_TO_CREATE_PIF_FILE_RC -42
#define UNABLE_TO_OPEN_ERROR_CODE_TEMP_FILE_RC -43
#define UNABLE_TO_OPEN_PIF_TEMP_FILE_RC -44
#define BAD_ERROR_CODE_TEMP_FILE_RC -45
#define INVALID_EXECUTABLE_FORMAT_RC -46
#define SYSTEM_FAILED_TO_EXECUTE_PROGRAM_RC -47
#define WDOSRC_FILE_NOT_FOUND_RC -48
#define FIOERROR_CREATING_TIMER_RC -49
#define FIOBREAK_KEY_PRESSED_RC -50
#define SLKSHELL_FILE_NOT_FOUND_RC -51
#define FIOINVALID_ARGUMENT_RC -52
#define EOF_RC -53
#define ARGFILE_NOT_FOUND_RC -54
#define ARGACCESS_DENIED_RC -55
#define ARGPATH_NOT_FOUND_RC -56
#define ARGUNABLE_TO_OPEN_FILE_RC -57
#define MEMBER_IN_USE_RC -58
#define DATASET_IN_USE_RC -59
#define DATASET_OR_MEMBER_IN_USE_RC -60
#define VOLUME_OUT_OF_SPACE_RC -61
#define DATASET_OUT_OF_EXTENT_RC -62
#define PDS_DIR_OUT_OF_SPACE_RC -63
#define DATASET_IO_RC -64
#define UNSUPPORTED_DATASET_TYPE_RC -65
#define DATASET_NOT_PDS_RC -66
#define PDS_MEMBER_NOT_FOUND_RC -67
#define NO_MORE_DDNAME_RC -68
#define UNABLE_TO_ALLOCATE_DDNAME_TO_DATASET_RC -69
#define DATASET_NOT_SEQUENTIAL_RC -70
#define UNSUPPORTED_DATASET_OPERATION_RC -71
#define INVALID_DATASET_NAME_RC -72
#define INVALID_PDS_MEMBER_NAME_RC -73
#define INSUFFICIENT_ACCESS_TO_DATASET_RC -74
#define UNABLE_TO_UPDATE_PDS_MEMBER_DIRECTORY_RC -75
#define INVALID_DATASET_PASSWORD_RC -76
#define DATASET_NOT_FOUND_RC -77
#define CANT_ACCESS_INTERNAL_READER_RC -78
#define CANT_WRITE_TO_SYSLOG_RC -79
#define CANT_LOAD_ASSEMBLER_MODULES_RC -80
#define CANT_QUERY_SYSTEM_DATASET_LISTING_RC -81
#define INSUFFICIENT_SPILL_DISK_SPACE_RC -82
#define INSUFFICIENT_LOG_DISK_SPACE_RC -83
#define USER_LOG_TOO_LARGE_RC -84
#define URL_BAD_RC -85
#define URL_PROTO_NOT_SUPPORTED_RC -86
#define URL_ERROR_READING_RESPONSE_RC -87
#define URL_STATUS_RC -88
#define URL_MOVED_RC -89
#define URL_RESPONSE_NOT_SUPPORTED_RC -90
#define VSRC_INVALID_ARGUMENT -91
#define BUFFER_OVERFLOW_RC -92
#define ERROR_CREATING_REGISTRY_VALUE_RC -93
#define ERROR_CREATING_REGISTRY_KEY_RC -94
#define VSRC_OPERATION_CANCELLED -95
#define VSRC_OPERATION_NOT_FINISHED -96
#define VSRC_POTENTIAL_DEADLOCK_DETECTED -97
#define VSRC_UNABLE_TO_GET_PROCESS_EXIT_CODE -98

///////////////////////////////////////////////////////////////////////////////
// SOCK
///////////////////////////////////////////////////////////////////////////////

#define SOCK_GENERAL_ERROR_RC -100
#define SOCK_INIT_FAILED_RC -101
#define SOCK_NOT_INIT_RC -102
#define SOCK_BAD_HOST_RC -103
#define SOCK_NO_MORE_SOCKETS_RC -104
#define SOCK_TIMED_OUT_RC -105
#define SOCK_BAD_PORT_RC -106
#define SOCK_BAD_SOCKET_RC -107
#define SOCK_SOCKET_NOT_CONNECTED_RC -108
#define SOCK_WOULD_BLOCK_RC -109
#define SOCK_NET_DOWN_RC -110
#define SOCK_NOT_ENOUGH_MEMORY_RC -111
#define SOCK_SIZE_ERROR_RC -112
#define SOCK_NO_MORE_DATA_RC -113
#define SOCK_ADDR_NOT_AVAILABLE_RC -114
#define SOCK_NOT_LISTENING_RC -115
#define SOCK_NO_CONN_PENDING_RC -116
#define SOCK_CONN_ABORTED_RC -117
#define SOCK_CONN_RESET_RC -118
#define SOCK_SHUTDOWN_RC -119
#define SOCK_CONNECTION_CLOSED_RC -120
#define SOCK_NO_PROTOCOL_RC -121
#define SOCK_CONN_REFUSED_RC -122
#define SOCK_TRY_AGAIN_RC -123
#define SOCK_NO_RECOVERY_RC -124
#define SOCK_IN_USE_RC -125

///////////////////////////////////////////////////////////////////////////////
// CFORMAT
///////////////////////////////////////////////////////////////////////////////

#define CFERROR_GENERAL_ERROR_RC -200
#define CFERROR_EOF_UNEXPECTED_RC -201
#define CFERROR_SYMBOL_UNEXPECTED_RC -202
#define CFERROR_RIGHTPAREN_EXPECTED_RC -203
#define CFERROR_RIGHTBRACE_EXPECTED_RC -204
#define CFERROR_RIGHTBRACKET_EXPECTED_RC -205
#define CFERROR_LEFTPAREN_EXPECTED_RC -206
#define CFERROR_LEFTBRACE_EXPECTED_RC -207
#define CFERROR_LEFTBRACKET_EXPECTED_RC -208
#define CFERROR_RIGHTPAREN_UNEXPECTED_RC -209
#define CFERROR_RIGHTBRACE_UNEXPECTED_RC -210
#define CFERROR_RIGHTBRACKET_UNEXPECTED_RC -211
#define CFERROR_LEFTPAREN_UNEXPECTED_RC -212
#define CFERROR_LEFTBRACE_UNEXPECTED_RC -213
#define CFERROR_LEFTBRACKET_UNEXPECTED_RC -214
#define CFERROR_CASE_UNEXPECTED_RC -215
#define CFERROR_COLON_EXPECTED_RC -216
#define CFERROR_SEMI_EXPECTED_RC -217
#define CFERROR_PP_UNEXPECTED_RC -218
#define CFERROR_WHILE_EXPECTED_RC -219
#define CFERROR_ELSE_UNEXPECTED_RC -220
#define CFERROR_ERROR_IN_TEMPLATE_RC -221
#define CFERROR_ENDSUBMENU_UNEXPECTED_RC -222
#define CFERROR_SUBMENU_UNEXPECTED_RC -223
#define CFERROR_MENU_UNEXPECTED_RC -224
#define CFERROR_CATCH_UNEXPECTED_RC -225
#define CFERROR_FINALLY_UNEXPECTED_RC -226
#define CFERROR_UNHANDLED_SYNTAX_RC -227

///////////////////////////////////////////////////////////////////////////////
// VSUPDATE
///////////////////////////////////////////////////////////////////////////////

#define VSUPDATE_LICENSE_TRANSFERRED_RC -350
#define VSUPDATE_HELP_RC -351
#define VSUPDATE_INVALID_SERIAL_NUMBER_RC -352
#define VSUPDATE_HELP_WIN_RC -353
#define VSUPDATE_INVALID_LICENSE_RC -354
#define VSUPDATE_INVALID_PACKS_RC -355
#define VSUPDATE_INCORRECT_ARCHITECTURE_RC -356
#define VSUPDATE_DLL_ONLY_FOR_WINDOWS_RC -357

///////////////////////////////////////////////////////////////////////////////
// KBIO
///////////////////////////////////////////////////////////////////////////////

#define UNABLE_TO_INIT_CONSOLE_RC -500

///////////////////////////////////////////////////////////////////////////////
// HFORMAT
///////////////////////////////////////////////////////////////////////////////

#define HFERROR_GENERAL_ERROR_RC -700
#define HFERROR_EOF_UNEXPECTED_RC -701

///////////////////////////////////////////////////////////////////////////////
// SLICKEDITOR
///////////////////////////////////////////////////////////////////////////////

#define SLICK_EDITOR_VERSION_RC -2000
#define SPILL_FILE_TOO_LARGE_RC -2001
#define ON_RC -2002
#define OFF_RC -2003
#define EXPECTING_IGNORE_OR_EXACT_RC -2004
#define ERROR_IN_MARGIN_SETTINGS_RC -2005
#define ERROR_IN_TAB_SETTINGS_RC -2006
#define UNKNOWN_COMMAND_RC -2007
#define MISSING_FILENAME_RC -2008
#define TOO_MANY_FILES_RC -2009
#define TOO_MANY_SELECTIONS_RC -2010
#define LINES_TRUNCATED_RC -2011
#define TEXT_ALREADY_SELECTED_RC -2012
#define TEXT_NOT_SELECTED_RC -2013
#define INVALID_SELECTION_TYPE_RC -2014
#define SOURCE_DEST_CONFLICT_RC -2015
#define NEW_FILE_RC -2016
#define LINE_SELECTION_REQUIRED_RC -2017
#define BLOCK_SELECTION_REQUIRED_RC -2018
#define TOO_MANY_GROUPS_RC -2019
#define MACRO_FILE_NOT_FOUND_RC -2020
#define TREE_CANNOT_DELETE_ROOT_NODE_RC -2021
#define HIT_ANY_KEY_RC -2023
#define BOTTOM_OF_FILE_RC -2024
#define TOP_OF_FILE_RC -2025
#define INVALID_POINT_RC -2026
#define TYPE_ANY_KEY_RC -2027
#define TOO_MANY_WINDOWS_RC -2028
#define NOT_ENOUGH_MEMORY_RC -2029
#define PRESS_ANY_KEY_TO_CONTINUE_RC -2030
#define SPILL_FILE_IO_ERROR_RC -2031
#define TYPE_NEW_DRIVE_LETTER_RC -2032
#define NOTHING_TO_UNDO_RC -2033
#define NOTHING_TO_REDO_RC -2034
#define LINE_OR_BLOCK_SELECTION_REQUIRED_RC -2035
#define INVALID_SELECTION_HANDLE_RC -2036
#define SEARCHING_AND_REPLACING_RC -2037
#define COMMAND_CANCELLED_RC -2038
#define ERROR_CREATING_SEMAPHORE_RC -2039
#define ERROR_CREATING_THREAD_RC -2040
#define ERROR_CREATING_QUEUE_RC -2041
#define PROCESS_ALREADY_RUNNING_RC -2042
#define CANT_FIND_INIT_PROGRAM_RC -2043
#define CMDLINE_TOO_LONG_RC -2044
#define SERIAL_NUMBER_RC -2045
#define UNRECOGNIZED_STATE_FILE_FORMAT_RC -2046
#define PACKAGE_LICENSES_RC -2047
#define UNABLE_TO_CREATE_SPILL_FILE_RC -2049
#define UNABLE_TO_DISPLAY_POPUP_RC -2052
#define MENU_HANDLE_MUST_BE_POPUP_RC -2053
#define MENU_HANDLE_CAN_NOT_BE_POPUP_RC -2054
#define INVALID_MENU_HANDLE_RC -2055
#define MENU_HANDLE_ALREADY_ATTACHED_TO_WINDOW_RC -2056
#define THIS_BORDER_STYLE_DOES_NOT_SUPPORT_MENUS_RC -2057
#define NOT_USED7_RC -2058
#define COMMAND_NOT_ALLOWED_WHEN_AW_IS_ICON_RC -2059
#define COMMAND_NOT_ALLOWED_WHEN_NCW_RC -2060
#define SLKWAIT_PROGRAM_NOT_FOUND_RC -2061
#define SIZE_RC -2062
#define MOVE_RC -2063
#define CLOSE_RC -2064
#define MINIMIZE_RC -2065
#define MAXIMIZE_RC -2066
#define NEXTWINDOW_RC -2067
#define RESTORE_RC -2068
#define TASKLIST_RC -2069
#define CLOSE_APPLICATION_RC -2070
#define WINDOW_MENU_RC -2071
#define APPLICATION_MENU_RC -2072
#define PROPERTY_OR_METHOD_NOT_ALLOWED_RC -2073
#define UNABLE_TO_CREATE_TIMER_RC -2074
#define TIMEOUT_WATING_FOR_PROCESS_INIT_RC -2075
#define CANT_CREATE_MDI_FORM_OBJECT_RC -2076
#define FORM_OBJECT_CAN_NOT_BE_CLIPPED_CHILD_RC -2077
#define CONTROL_OBJECTS_MUST_HAVE_PARENT_RC -2078
#define INVALID_PARENT_WINDOW_RC -2079
#define INVALID_SORT_DATA_RC -2080
#define XTERM_PROGRAM_NOT_FOUND_RC -2081
#define OBJECT_MUST_BE_DISPLAYED_RC -2082
#define FORM_OR_CONTROL_DOES_NOT_HAVE_NAME_RC -2083
#define CLIPBOARD_OPERATION_NOT_SUPPORTED_RC -2084
#define UNABLE_TO_GET_CLIPBOARD_DATA_RC -2085
#define NOTHING_SELECTED_RC -2086
#define SYSTEM_CALL_FAILED_RC -2087
#define INVALID_OBJECT_HANDLE_RC -2088
#define FAILED_TO_LOAD_PRINTER_DRIVER_RC -2089
#define EXT_DEVICE_MODE_FUNCTION_NOT_FOUND_RC -2090
#define PRINTER_NOT_SET_UP_CORRECTLY_RC -2091
#define UNABLE_TO_START_PRINTER_RC -2092
#define PRINTER_FAILURE_RC -2093
#define LONG_STRING_MATCH_RC -2094
#define DDE_NOT_PROCESSED_RC -2095
#define DDE_BUSY_RC -2096
#define DDE_UNABLE_TO_CONNECT_RC -2097
#define DDE_ERROR_RC -2098
#define COMMAND_NOT_ALLOWED_IN_READ_ONLY_MODE_RC -2099
#define WEMU387_NOT_FOUND_OR_INVALID_RC -2100
#define FAILED_TO_BACKUP_FILE_RC -2101
#define FAILED_TO_BACKUP_FILE_ACCESS_DENIED_RC -2105
#define LINE_RC -2106
#define COL_RC -2107
#define INS_RC -2108
#define REP_RC -2109
#define DEMO_CANT_SAVE_FILES_RC -2110
#define FAILED_TO_BACKUP_FILE_INSUFFICIENT_DISK_SPACE_RC -2111
#define SLICK_C_CANT_CALL_DLL_FUNCTION_WITH_PVOID_RC -2112
#define FUNCTION_NOT_AVAILABLE_RC -2113
#define MACROS_WITH_DEFMAIN_MAY_NOT_BE_LOADED_RC -2114
#define APPNAME_RC -2115
#define VSRC_INSTANCE_ALREADY_RUNNING_RC -2121
#define VSRC_LINE_TOOLTIP_RC -2122
#define VSRC_COL_TOOLTIP_RC -2123
#define VSRC_MODE_TOOLTIP_RC -2124
#define VSRC_READWRITE_TOOLTIP_RC -2125
#define VSRC_INSREP_TOOLTIP_RC -2126
#define VSRC_SELECTION_TOOLTIP_RC -2127
#define NO_SELECTION_RC -2128
#define SELECTION_1LINE_RC -2129
#define SELECTION_LINES_RC -2130
#define SELECTION_1COLUMN_RC -2131
#define SELECTION_COLUMNS_RC -2132
#define SELECTION_BLOCK_RC -2133
#define VSRC_RECORD_MACRO_TOOLTIP_RC -2134
#define VSRC_ALERT_TOOLTIP_RC -2135
#define VSRC_LINES_LONGER_THAN_ALLOWED_LIMIT -2148
#define VSRC_LINE_TRUNCATED_TO_FIT_WITHIN_TRUNCATE_LENGTH_RC -2149
#define VSRC_THIS_OPERATION_IS_NOT_ALLOWED_AFTER_TRUNCATION_LENGTH -2150
#define VSRC_THIS_OPERATION_WOULD_CREATE_LINE_TOO_LONG -2151
#define VSRC_CURSOR_POSITION_PAST_TRUNCATION_LENGTH -2152
#define VSRC_OPERATION_ONLY_ALLOWED_WHEN_TRUNCATION_LENGTH_IS_ZERO -2153
#define VSRC_SELECTION_NOT_VALID_FOR_OPERATION -2154
#define VSRC_RECORD_WIDTH_OPTION_NOT_SUPPORTED_FOR_UTF8 -2155
#define VSRC_CODE_PAGE_NOT_INSTALLED_OR_NOT_VALID_RC -2156
#define VSRC_CODE_PAGE_TO_CODE_PAGE_TRANSLATIONS_NOT_SUPPORTED -2157
#define VSRC_THIS_EBCDIC_TRANSLATION_IS_NOT_SUPPORTED -2158
#define VSRC_COMMAND_IS_DISABLED_FOR_THIS_OBJECT_OR_STATE -2159
#define VSRC_COMMAND_NOT_IMPLEMENTED -2160
#define VSRC_MENU_NOT_FOUND -2161
#define VSRC_TOOL_WINDOW_NOT_FOUND -2162
#define VSRC_FORM_NOT_FOUND -2163
#define VSRC_LICENSE_EXPIRED -2164
#define VSRC_MUST_BE_USING_QT -2165
#define VSRC_FUNCTION_NOT_SUPPORTED_WHEN_USING_QT -2166
#define VSRC_SAVE_COMPLETION_STATUS -2167
#define VSRC_SEARCHING_STATUS -2167
#define VSRC_REPLACED_ONE_STATUS -2168
#define VSRC_REPLACED_MULTIPLE_STATUS -2169

///////////////////////////////////////////////////////////////////////////////
// REGEX
///////////////////////////////////////////////////////////////////////////////

#define INVALID_REGULAR_EXPRESSION_RC -2500
#define EOL1_RC -2501
#define EOL2_RC -2502
#define RE_EOF_RC -2503
#define REBREAK_KEY_PRESSED_RC -2504

///////////////////////////////////////////////////////////////////////////////
// VSCR
///////////////////////////////////////////////////////////////////////////////

#define VUNSUPPORTED_GRAPHICS_FORMAT_RC -2550
#define VINVALID_BITMAP_FILE_RC -2551

///////////////////////////////////////////////////////////////////////////////
// SLICKI
///////////////////////////////////////////////////////////////////////////////

#define INCORRECT_VERSION_RC -3000
#define NO_MAIN_ENTRY_POINT_RC -3001
#define INTERPRETER_OUT_OF_MEMORY_RC -3002
#define PROCEDURE_NOT_FOUND_RC -3003
#define MODULE_ALREADY_LOADED_RC -3006
#define CANT_REMOVE_MODULE_RC -3007
#define NUMERIC_OVERFLOW_RC -3008
#define INVALID_NUMBER_ARGUMENT_RC -3009
#define RECURSION_TOO_DEEP_RC -3010
#define INVALID_NUMBER_OF_PARAMETERS_RC -3011
#define OUT_OF_STRING_SPACE_RC -3012
#define EXPRESSION_STACK_OVERFLOW_RC -3013
#define ILLEGAL_OPCODE_RC -3014
#define INVALID_ARGUMENT_RC -3015
#define LOOP_STACK_OVERFLOW_RC -3016
#define DIVIDE_BY_ZERO_RC -3017
#define INVALID_CALL_BY_REFERENCE_RC -3018
#define PROCEDURE_NEEDS_MORE_ARGS_RC -3019
#define BREAK_KEY_PRESSED_RC -3020
#define CANT_WRITE_STATE_DURING_REL_RC -3021
#define STRING_NOT_FOUND_RC -3022
#define NOT_USED_1_RC -3023
#define COMMAND_NOT_FOUND_RC -3024
#define FUNCTION_NOT_SUPPORTED_IN_DOS_RC -3027
#define FUNCTION_NOT_SUPPORTED_IN_OS2_RC -3028
#define INVALID_NAME_INDEX_RC -3029
#define INVALID_OPTION_RC -3030
#define NOT_ENOUGH_MEMORY_TO_CREATE_MENU_RC -3040
#define NO_FILE_ACTIVE_RC -3041
#define OBJECT_REFERENCED_BUT_DOES_NOT_EXIST_RC -3042
#define CONTROL_REFERENCED_BUT_DOES_NOT_EXIST_RC -3045
#define EVENT_TABLE_REFERENCED_BUT_DOES_NOT_EXIST_RC -3048
#define VSAPI_DLL_NOT_FOUND_RC -3051
#define ERROR_LOADING_DLL_RC -3055
#define DLL_FUNCTION_NOT_FOUND_RC -3058
#define INVALID_DLLTYPE_RC -3061
#define ARGINVALID_ARGUMENT_RC -3064
#define DELETED_ELEMENT_RC -3066
#define WARNINGSTRINGLEN_RC -3067
#define INVALID_ARRAY_RC -3070
#define ARRAY_OR_HASH_TABLE_ELEMENT_NOT_INITIALIZED_RC -3071
#define INVALID_HVAR_ARGUMENT_RC -3072
#define INVALID_POINTER_ARGUMENT_RC -3073
#define CALL_WITH_UNINITIALIZED_VARIABLE_RC -3074
#define CALL_WITH_NOT_ENOUGH_ARGUMENTS_RC -3079
#define INVALID_FUNCTION_POINTER_RC -3084
#define WARNINGARRAYSIZE_RC -3085
#define WARNING_POSSIBLE_REFERENCE_TO_CONTROL_WHICH_DOES_NOT_EXIST_RC -3088
#define CANT_SUBSCRIPT_STACK_COPY_OF_ARRAY_OR_HASH_TABLE_RC -3095
#define VSRC_LOAD_FILES_WITH_PLUSC_OPTION_DEPRECATED -3096
#define VSRC_LOAD_FILES_WITH_PLUSV_OPTION_DEPRECATED -3097
#define CLASS_NAME_NOT_FOUND_RC -3098
#define CLASS_MEMBER_NOT_FOUND_RC -3099
#define EXPECTING_CLASS_INSTANCE_RC -3100
#define SLICKC_ASSERTION_FAILURE_RC -3101
#define SLICKC_ATTACH_DEBUGGER_RC -3102
#define SLICK_CMD_LINE_USAGE_WIN -3103
#define SLICK_CMD_LINE_USAGE_NIX -3104
#define SLICK_STOP_OP -3105

///////////////////////////////////////////////////////////////////////////////
// SPELL
///////////////////////////////////////////////////////////////////////////////

#define SPELL_TEST_RC -3500
#define SPELL_FILE_NOT_FOUND_RC -3501
#define SPELL_ERROR_OPENING_MAIN_DICT_FILE_RC -3504
#define SPELL_ERROR_OPENING_USER_DICT_FILE_RC -3507
#define SPELL_NOT_ENOUGH_MEMORY_RC -3510
#define SPELL_ERROR_READING_MAIN_INDEX_RC -3511
#define SPELL_ERROR_OPENING_COMMON_DICT_RC -3514
#define SPELL_COMMON_DICT_TOO_LARGE_RC -3517
#define SPELL_ERROR_READING_COMMON_DICT_RC -3518
#define SPELL_USER_DICT_TOO_LARGE_RC -3521
#define SPELL_ERROR_READING_USER_DICT_RC -3524
#define SPELL_ERROR_UPDATING_USER_DICT_FILE_RC -3527
#define SPELL_ACCESS_DENIED_RC -3530
#define SPELL_OUT_OF_DISK_SPACE_RC -3533
#define SPELL_ERROR_READING_MAIN_DICT_RC -3536
#define SPELL_WORD_NOT_FOUND_RC -3537
#define SPELL_CAPITALIZATION_RC -3538
#define SPELL_WORD_TOO_SMALL_RC -3539
#define SPELL_WORD_TOO_LARGE_RC -3540
#define SPELL_WORD_INVALID_RC -3541
#define SPELL_REPLACE_WORD_RC -3542
#define SPELL_HISTORY_TOO_LARGE_RC -3543
#define SPELL_USER_DICT_NOT_LOADED_RC -3544
#define SPELL_NO_MORE_WORDS_RC -3545
#define SPELL_REPEATED_WORD_RC -3546

///////////////////////////////////////////////////////////////////////////////
// CLEX
///////////////////////////////////////////////////////////////////////////////

#define CLEX_NOT_ENOUGH_MEMORY_RC -3547
#define CLEX_TOO_MANY_MLCOMMENTS_DEFINED_RC -3548
#define CLEX_IDENTIFIER_MLCOMMENTS_NOT_SUPPORTED_RC -3549
#define CLEX_TOO_MANY_CFLINECOMMENTS_DEFINED_RC -3550
#define CLEX_IDCHARS_MUST_BE_DEFINED_FIRST_RC -3551
#define CLEX_INVALID_STYLE_RC -3552
#define CLEX_INVALID_MLCOMMENT_RC -3553
#define CLEX_INVALID_LINECOMMENT_RC -3554
#define CLEX_INVALID_NAME_RC -3555
#define CLEX_FILE_NOT_FOUND_RC -3556
#define CLEX_ACCESS_DENIED_RC -3557
#define CLEX_UNABLE_TO_OPEN_FILE_RC -3558
#define CLEX_INVALID_IDCHARS_RC -3559
#define CLEX_NO_INFO_FOR_FILE_RC -3560

///////////////////////////////////////////////////////////////////////////////
// BTREE
///////////////////////////////////////////////////////////////////////////////

#define VS_TAG_FLAG_VIRTUAL_RC -3860
#define VS_TAG_FLAG_STATIC_RC -3861
#define VS_TAG_FLAG_PUBLIC_RC -3862
#define VS_TAG_FLAG_PACKAGE_RC -3863
#define VS_TAG_FLAG_PROTECTED_RC -3864
#define VS_TAG_FLAG_PRIVATE_RC -3865
#define VS_TAG_FLAG_CONST_RC -3866
#define VS_TAG_FLAG_FINAL_RC -3867
#define VS_TAG_FLAG_ABSTRACT_RC -3868
#define VS_TAG_FLAG_INLINE_RC -3869
#define VS_TAG_FLAG_OPERATOR_RC -3870
#define VS_TAG_FLAG_CONSTRUCTOR_RC -3871
#define VS_TAG_FLAG_VOLATILE_RC -3872
#define VS_TAG_FLAG_TEMPLATE_RC -3873
#define VS_TAG_FLAG_INCLASS_RC -3874
#define VS_TAG_FLAG_DESTRUCTOR_RC -3875
#define VS_TAG_FLAG_SYNCHRONIZED_RC -3876
#define VS_TAG_FLAG_TRANSIENT_RC -3877
#define VS_TAG_FLAG_NATIVE_RC -3878
#define VS_TAG_FLAG_MACRO_RC -3879
#define VS_TAG_FLAG_EXTERN_RC -3880
#define VS_TAG_FLAG_MAYBE_VAR_RC -3881
#define VS_TAG_FLAG_ANONYMOUS_RC -3882
#define VS_TAG_FLAG_MUTABLE_RC -3883
#define VS_TAG_FLAG_EXTERN_MACRO_RC -3884
#define VS_TAG_FLAG_LINKAGE_RC -3885
#define VS_TAG_FLAG_PARTIAL_RC -3886
#define VS_TAG_FLAG_IGNORE_RC -3887
#define VS_TAG_FLAG_FORWARD_RC -3888
#define VS_TAG_FLAG_OPAQUE_RC -3889
#define BT_KEY_ALREADY_EXISTS_RC -3900
#define BT_RECORD_NOT_FOUND_RC -3901
#define BT_UNABLE_TO_RW_FILE_RC -3902
#define BT_DATABASE_CORRUPT_RC -3903
#define BT_RECORD_LENGTH_TOO_LARGE_RC -3904
#define BT_INCORRECT_VERSION_RC -3905
#define BT_INCORRECT_MAGIC_RC -3906
#define BT_TOO_MANY_KEYS_RC -3907
#define BT_FEATURE_NOT_FINISHED_RC -3908
#define BT_FIELD_IS_FIXED_LENGTH_RC -3909
#define BT_FIELD_IS_VARIABLE_LENGTH_RC -3910
#define BT_BLOCK_FULL_RC -3911
#define BT_UNABLE_TO_DELETE_RC -3912
#define BT_INVALID_BLOCK_SIZE_RC -3913
#define BT_MISSING_REQUIRED_FIELD_RC -3914
#define BT_ERROR_UPDATING_INDEX_RC -3915
#define BT_ERROR_CREATING_TABLE_RC -3916
#define BT_ERROR_CREATING_INDEX_RC -3917
#define BT_ERROR_OPENING_TABLE_RC -3918
#define BT_ERROR_OPENING_INDEX_RC -3919
#define BT_FEATURE_NOT_ALLOWED_RC -3920
#define BT_TABLE_NOT_FOUND_RC -3921
#define BT_KEY_NOT_FOUND_RC -3922
#define BT_FIELD_NOT_FOUND_RC -3923
#define BT_INDEX_NOT_FOUND_RC -3924
#define BT_INTERNAL_ERROR_RC -3925
#define BT_FIELD_NOT_SEARCHABLE_RC -3926
#define BT_FIELD_ALREADY_EXISTS_RC -3927
#define BT_INDEX_ALREADY_EXISTS_RC -3928
#define BT_TABLE_ALREADY_EXISTS_RC -3929
#define BT_FIELD_NAME_REQUIRED_RC -3930
#define BT_INDEX_NAME_REQUIRED_RC -3931
#define BT_TABLE_NAME_REQUIRED_RC -3932
#define BT_DATABASE_NAME_REQUIRED_RC -3933
#define BT_FIELD_INVALID_RC -3934
#define BT_INVALID_DB_HANDLE_RC -3935
#define BT_INVALID_TAG_TYPE_RC -3936
#define BT_INVALID_TABLE_HANDLE_RC -3937
#define BT_INVALID_INDEX_HANDLE_RC -3938
#define BT_INVALID_SEEKPOS_RC -3939
#define BT_DATABASE_IS_FOR_UNIX_RC -3940
#define BT_DATABASE_IS_FOR_DOS_RC -3941
#define BT_DATABASE_IS_READ_ONLY_RC -3942
#define BT_INDEX_TABLE_MISMATCH_RC -3943
#define BT_INCORRECT_BLOCKSIZE_RC -3944
#define BT_TOO_MANY_FIELDS_RC -3945
#define BT_TOO_MANY_INDEXES_RC -3946
#define BT_TOO_MANY_TABLES_RC -3947
#define BT_INVALID_NODE_RC -3948
#define BT_INVALID_TABLE_RC -3949
#define BT_INVALID_DATABASE_RC -3950
#define BT_INVALID_BLOCK_RC -3951
#define BT_TOO_MANY_SEEKPOS_RC -3952
#define BT_SEEKPOS_NOT_FOUND_RC -3953
#define BT_SEEKPOS_ALREADY_EXISTS_RC -3954
#define BT_BRANCH_NOT_FOUND_RC -3955
#define BT_CACHE_SIZE_TOO_SMALL_RC -3956
#define BT_INVALID_FILE_TYPE_RC -3957
#define BT_SESSION_NOT_FOUND_RC -3958
#define BT_TOO_MANY_SESSIONS_RC -3959
#define BT_READWRITE_NOT_ALLOWED_RC -3960
#define BT_CREATE_NOT_ALLOWED_RC -3961
#define BT_INVALID_SESSION_HANDLE_RC -3962
#define BT_INVALID_DATABASE_TYPE_RC -3963
#define BT_HASH_NODE_FULL_RC -3964
#define BT_HASH_INDEX_NOT_FOUND_RC -3965
#define BT_INVALID_HASH_INDEX_RC -3966
#define BT_INVALID_HASH_NODE_SIZE_RC -3967
#define BT_TOO_MANY_SYMBOLS_RC -3968
#define BT_TABLE_NO_NEXT_PREV_RC -3969
#define BT_RECORD_LENGTH_TOO_SMALL_RC -3970
#define BT_INDEX_REQUIRES_NEXT_PREV_RC -3971
#define BT_FEATURE_IS_OBSOLETE_RC -3972
#define TAGGING_SEARCHING_FOUND_OF_TOTAL_RC -3973
#define TAGGING_TIMEOUT_RC -3974
#define TAG_DATABASE_ALREADY_BEING_REBUILT_RC -3975
#define BACKGROUND_TAGGING_NOT_SUPPORTED_RC -3976
#define EMBEDDED_TAGGING_NOT_SUPPORTED_RC -3977
#define LEFTOVER_FILE_REMOVED_FROM_DATABASE_RC -3978
#define TAGGING_NOT_SUPPORTED_FOR_FILE_RC -3979
#define FILE_REMOVED_FROM_DATABASE_RC -3980
#define BACKGROUND_TAGGING_COMPLETE_RC -3981
#define BACKGROUND_TAGGING_IS_FINDING_FILES_RC -3982
#define BT_DATABASE_FULL_RC -3983
#define BT_THREADS_CANNOT_CLOSE_FILES_RC -3984
#define TAGGING_CAN_NOT_REBUILD_TAG_FILE_WITH_ALL_FILES_MISSING_RC -3985
#define BACKGROUND_TAGGING_PREEMPTED_RC -3986
#define VSTAG_TYPE_DEFAULT_RC -4000
#define VSTAG_TYPE_PROC_RC -4001
#define VSTAG_TYPE_PROTO_RC -4002
#define VSTAG_TYPE_DEFINE_RC -4003
#define VSTAG_TYPE_TYPEDEF_RC -4004
#define VSTAG_TYPE_GVAR_RC -4005
#define VSTAG_TYPE_STRUCT_RC -4006
#define VSTAG_TYPE_ENUMC_RC -4007
#define VSTAG_TYPE_ENUM_RC -4008
#define VSTAG_TYPE_CLASS_RC -4009
#define VSTAG_TYPE_UNION_RC -4010
#define VSTAG_TYPE_LABEL_RC -4011
#define VSTAG_TYPE_INTERFACE_RC -4012
#define VSTAG_TYPE_CONSTRUCTOR_RC -4013
#define VSTAG_TYPE_DESTRUCTOR_RC -4014
#define VSTAG_TYPE_PACKAGE_RC -4015
#define VSTAG_TYPE_VAR_RC -4016
#define VSTAG_TYPE_LVAR_RC -4017
#define VSTAG_TYPE_CONSTANT_RC -4018
#define VSTAG_TYPE_FUNCTION_RC -4019
#define VSTAG_TYPE_PROPERTY_RC -4020
#define VSTAG_TYPE_PROGRAM_RC -4021
#define VSTAG_TYPE_LIBRARY_RC -4022
#define VSTAG_TYPE_PARAMETER_RC -4023
#define VSTAG_TYPE_IMPORT_RC -4024
#define VSTAG_TYPE_FRIEND_RC -4025
#define VSTAG_TYPE_DATABASE_RC -4026
#define VSTAG_TYPE_TABLE_RC -4027
#define VSTAG_TYPE_COLUMN_RC -4028
#define VSTAG_TYPE_INDEX_RC -4029
#define VSTAG_TYPE_VIEW_RC -4030
#define VSTAG_TYPE_TRIGGER_RC -4031
#define VSTAG_TYPE_FORM_RC -4032
#define VSTAG_TYPE_MENU_RC -4033
#define VSTAG_TYPE_CONTROL_RC -4034
#define VSTAG_TYPE_EVENTTAB_RC -4035
#define VSTAG_TYPE_PROCPROTO_RC -4036
#define VSTAG_TYPE_TASK_RC -4037
#define VSTAG_TYPE_INCLUDE_RC -4038
#define VSTAG_TYPE_FILE_RC -4039
#define VSTAG_TYPE_GROUP_RC -4040
#define VSTAG_TYPE_SUBFUNC_RC -4041
#define VSTAG_TYPE_SUBPROC_RC -4042
#define VSTAG_TYPE_CURSOR_RC -4043
#define VSTAG_TYPE_TAG_RC -4044
#define VSTAG_TYPE_TAGUSE_RC -4045
#define VSTAG_TYPE_STATEMENT_RC -4046
#define VSTAG_TYPE_ANNOTYPE_RC -4047
#define VSTAG_TYPE_ANNOTATION_RC -4048
#define VSTAG_TYPE_CALL_RC -4049
#define VSTAG_TYPE_IF_RC -4050
#define VSTAG_TYPE_LOOP_RC -4051
#define VSTAG_TYPE_BREAK_RC -4052
#define VSTAG_TYPE_CONTINUE_RC -4053
#define VSTAG_TYPE_RETURN_RC -4054
#define VSTAG_TYPE_GOTO_RC -4055
#define VSTAG_TYPE_TRYCATCH_RC -4056
#define VSTAG_TYPE_PP_RC -4057
#define VSTAG_TYPE_BLOCK_RC -4058
#define VSTAG_TYPE_MIXIN_RC -4059
#define VSTAG_TYPE_TARGET_RC -4060
#define VSCODEHELPRC_CONTEXT_NOT_VALID -4061
#define VSCODEHELPRC_NOT_IN_ARGUMENT_LIST -4062
#define VSCODEHELPRC_NO_HELP_FOR_FUNCTION -4063
#define VSCODEHELPRC_NO_SYMBOLS_FOUND -4064
#define VSCODEHELPRC_CONTEXT_EXPRESSION_TOO_COMPLEX -4065
#define VSCODEHELPRC_UNABLE_TO_EVALUATE_CONTEXT -4066
#define VSCODEHELPRC_DOT_FOR_POINTER -4067
#define VSCODEHELPRC_DASHGREATER_FOR_NON_POINTER -4068
#define VSCODEHELPRC_INVALID_NEW_EXPRESSION -4069
#define VSCODEHELPRC_PARENTHESIS_MISMATCH -4070
#define VSCODEHELPRC_BRACKETS_MISMATCH -4071
#define VSCODEHELPRC_DASHGREATER_FOR_PTR_TO_POINTER -4072
#define VSCODEHELPRC_SUBSCRIPT_BUT_NOT_ARRAY_TYPE -4073
#define VSCODEHELPRC_OVERLOADED_RETURN_TYPE -4074
#define VSCODEHELPRC_NOT_A_TEMPLATE_CLASS -4075
#define VSCODEHELPRC_RETURN_TYPE_NOT_FOUND -4076
#define VSCODEHELPRC_TEMPLATE_ARGS_MISMATCH -4077
#define VSCODEHELPRC_BUILTIN_TYPE -4078
#define VSCODEHELPRC_NO_LABELS_DEFINED -4079
#define VSCODEHELPRC_DOT_FOR_ARRAY -4080
#define VSCODEHELPRC_LIST_PARAMS_NOT_SUPPORTED -4081
#define VSCODEHELPRC_RETURN_TYPE_IS_VOID -4082
#define VSCODEHELPRC_LIST_MEMBERS_TIMEOUT -4083
#define VSCODEHELPRC_FUNCTION_HELP_TIMEOUT -4084
#define VSCODEHELPRC_LIST_MEMBERS_LIMITED -4083

///////////////////////////////////////////////////////////////////////////////
// BSC
///////////////////////////////////////////////////////////////////////////////

#define BSC_INCORRECT_EXTENSION_RC -4100
#define BSC_ERROR_OPENING_FILE_RC -4101
#define BSC_NO_INSTANCES_RC -4102
#define BSC_ONLY_ON_WINDOWS_RC -4103
#define BSC_CANNOT_OPEN_DLL_RC -4104

///////////////////////////////////////////////////////////////////////////////
// JAVA
///////////////////////////////////////////////////////////////////////////////

#define JAVA_CLASS_INCOMPLETE_HEADER_RC -4125
#define JAVA_CLASS_BAD_MAGIC_NUMBER_RC -4126
#define JAVA_CLASS_UNSUPPORTED_VERSION_RC -4127
#define JAVA_CLASS_UNKNOWN_CONSTANT_TYPE_RC -4128
#define JAVA_CLASS_ATTRIBUTE_LENGTH_MISMATCH_RC -4129
#define JAVA_CLASS_SOURCE_NOT_FOUND_RC -4130
#define JAVA_CLASS_INVALID_CONSTANT_INDEX_RC -4131
#define JAVA_CLASS_STRING_NOT_FOUND_RC -4132
#define JAVA_JAR_INCOMPLETE_HEADER_RC -4133
#define JAVA_JAR_BAD_MAGIC_NUMBER_RC -4134
#define JAVA_JAR_UNSUPPORTED_VERSION_RC -4135
#define JAVA_JAR_DECOMPRESS_ERROR_RC -4136
#define JAVA_JAR_CORRUPT_HEADER_RC -4137

///////////////////////////////////////////////////////////////////////////////
// OBJECT
///////////////////////////////////////////////////////////////////////////////

#define OBJECT_FILE_INCOMPLETE_HEADER_RC -4150
#define OBJECT_FILE_BAD_MAGIC_NUMBER_RC -4151
#define OBJECT_FILE_UNRECOGNIZED_RC -4152
#define OBJECT_FILE_NO_DEBUG_RC -4153

///////////////////////////////////////////////////////////////////////////////
// METADATA
///////////////////////////////////////////////////////////////////////////////

#define METADATA_NOT_SUPPORTED_ON_UNIX_RC -4175
#define METADATA_CAN_NOT_CREATE_INSTANCE_RC -4176
#define METADATA_CAN_NOT_CREATE_IMPORTER_RC -4177

///////////////////////////////////////////////////////////////////////////////
// VSBUILD
///////////////////////////////////////////////////////////////////////////////

#define VSBUILDRC_USAGE -4200
#define VSBUILDRC_CANNOT_OPEN_FILE_2ARG -4201
#define VSBUILDRC_ERROR_READ_FILE_2ARG -4202
#define VSBUILDRC_CANNOT_USE_M_OPTION_1ARG -4203
#define VSBUILDRC_CANNOT_USE_C_OPTION_1ARG -4204
#define VSBUILDRC_CANNOT_USE_L_OPTION_1ARG -4205
#define VSBUILDRC_CANNOT_USE_NNN_OPTION_1ARG -4206
#define VSBUILDRC_CANNOT_USE_FILTER_OPTION_1ARG -4207
#define VSBUILDRC_WORKSPACE_FILE_NOT_FOUND_1ARG -4208
#define VSBUILDRC_HISTORY_FILE_NOT_FOUND_2ARG -4209
#define VSBUILDRC_PROJECT_FILE_NOT_FOUND_2ARG -4210
#define VSBUILDRC_NO_DEPENDENCIES_2ARG -4211
#define VSBUILDRC_DEPENDS_ON_3ARG -4212
#define VSBUILDRC_COMMAND_NOT_DEFINED_IN_PROJECT_3ARG -4213
#define VSBUILDRC_COULD_NOT_CHANGE_DIRECTORY_2ARG -4214
#define VSBUILDRC_CHANGED_TO_DIRECTORY_2ARG -4215
#define VSBUILDRC_NO_BUILD_COMMAND_FOR_PROJECT_2ARG -4216
#define VSBUILDRC_PROGRAM_NOT_FOUND_2ARG -4217
#define VSBUILDRC_ALL_FILES_HAVE_BEEN_COMPILED_1ARG -4218
#define VSBUILDRC_STOP_WITH_ERROR_3ARG -4219
#define VSBUILDRC_NO_CURRENT_PROJECT_1ARG -4220
#define VSBUILDRC_JAR_COMMAND_MUST_SPECIFY_F_OPTION_2ARG -4221
#define VSBUILDRC_JAR_COMMAND_MUST_SPECIFY_C_OR_U_OPTION_2ARG -4222
#define VSBUILDRC_UNKNOWN_OPTION_2ARG -4223
#define VSBUILDRC_UNABLE_TO_OPEN_TEMP_LIST_FILE_2ARG -4224
#define VSBUILDRC_OUT_OF_DISK_SPACE_WRITING_TO_TEMP_LIST_FILE_2ARG -4225
#define VSBUILDRC_CANNOT_INIT_DEPENDENCY_DATABASE_1ARG -4226
#define VSBUILDRC_INFINITE_COMMAND_RECURSION_1ARG -4227
#define VSBUILDRC_ERRORS_OCCURRED_1ARG -4228
#define VSBUILDRC_BUILD_SUCCESSFUL_1ARG -4229
#define VSBUILDRC_BUILDING_PROJECT_3ARG -4230
#define VSBUILDRC_REBUILDING_PROJECT_3ARG -4231
#define VSBUILDRC_JARRING_PROJECT_3ARG -4232
#define VSBUILDRC_JAVADOCING_PROJECT_3ARG -4233
#define VSBUILDRC_NO_FILES_IN_PROJECT_1ARG -4234
#define VSBUILDRC_DEPENDENCY_DATABASE_NOT_FOUND_1ARG -4235
#define VSBUILDRC_DEPENDENCY_DATABASE_OUTDATED_1ARG -4236
#define VSBUILDRC_NOTHING_TO_LINK_1ARG -4237
#define VSBUILDRC_INFINITE_LOOP_DETECTED_IN_COMMAND_2ARG -4238
#define VSBUILDRC_NO_CONFIG_SPECIFIED_1ARG -4239
#define VSBUILDRC_CONFIG_NOT_FOUND_3ARG -4240
#define VSBUILDRC_FILE_NOT_FOUND_2ARG -4241
#define VSBUILDRC_ERROR_SETTING_UP_ENVIRONMENT_1ARG -4242
#define VSBUILDRC_CLEANING_PROJECT_3ARG -4243
#define VSBUILDRC_CANNOT_REMOVE_FILE_2ARG -4244
#define VSBUILDRC_CPP_COMMAND_CHANGE_DETECTED_1ARG -4245
#define VSBUILDRC_JAVA_CONFIG_OR_COMMAND_CHANGE_DETECTED_1ARG -4246
#define VSBUILDRC_INVALID_FILE_FORMAT_2ARG -4247
#define VSBUILDRC_TARGET_REQUIRED_1ARG -4248
#define VSBUILDRC_TARGET_NOT_FOUND_4ARG -4249
#define VSBUILDRC_CANNOT_READ_DEPENDENCY_DATABASE_1ARG -4250
#define VSBUILDRC_ANT_HOME_NOT_FOUND_1ARG -4251
#define VSBUILDRC_CPP_OBJECT_COUNT_CHANGE_DETECTED_1ARG -4252
#define VSBUILDRC_VSBUILD_COMMAND_CANT_CHANGE_WORKSPACE_PROJECT_CONFIG_OR_TARGET_1ARG -4253
#define VSBUILDRC_TARGET_PROJECT_4ARG -4254
#define VSBUILDRC_INVALID_ARGUMENT_2ARG -4255
#define VSBUILDRC_NO_COMPILE_RULE_FOUND_FOR_FILE_2ARG -4256
#define VSBUILDRC_FILE_WRITTEN_TO_MULTIPLE_TIMES_2ARG -4257
#define VSBUILDRC_DATABASE_WRITTEN_TO_MULTIPLE_TIMES_2ARG -4258
#define VSBUILDRC_DEPENCY_FROM_NOT_FOUND_4ARG -2459

///////////////////////////////////////////////////////////////////////////////
// LICENSE
///////////////////////////////////////////////////////////////////////////////

#define VSLM_RUN_VSUPDATE_WIN_RC -4300
#define VSLM_RUN_VSUPDATE_OS2_RC -4301
#define VSLM_RUN_VSUPDATE_UNIX_RC -4302
#define VSLM_RUN_VSUPDATE_UNIXDLL_RC -4303
#define VSLM_SERIAL_NUMBER_NOT_VALID_RC -4304
#define VSLM_UNABLE_TO_OBTAIN_FLEXLM_LICENSE_RC -4305
#define VSLM_ERROR_SEEKING_TO_BEGINNING_RC -4306
#define VSLM_ERROR_SEEKING_TO_END_RC -4307
#define VSLM_ERROR_WRITING_TO_FILE_RC -4308
#define VSLM_ERROR_READING_LICENSE_FILE_RC -4309
#define VSLM_USER_NOT_FOUND_RC -4310
#define VSLM_ERROR_OPENING_OR_CREATING_RC -4311
#define VSLM_ERROR_OPENING_RC -4312
#define VSLM_SERIAL_NUMBER_AND_LICENSE_NOT_VALID_RC -4313
#define VSLM_UNABLE_TO_CREATE_LICENSE_MANAGER_DIR_RC -4314
#define VSLM_USER_NOT_AUTHORIZED_RC -4315
#define VSLM_LICENSE_LIMIT_REACHED_WIN_RC -4316
#define VSLM_LICENSE_LIMIT_REACHED_OS2_RC -4317
#define VSLM_LICENSE_LIMIT_REACHED_UNIX_RC -4318
#define VSTRIAL_FAILED_TO_OPEN_TRIAL_SIZE_FILE_RC -4319
#define VSTRIAL_ERROR_IN_TRIAL_SIZE_FILE_RC -4320
#define VSTRIAL_FAILED_TO_OPEN_TRIAL_EXECUTABLE_RC -4321
#define VSTRIAL_PATCH_SERIAL_NUMBER_AND_LICENSE_RC -4322
#define VSTRIAL_FAILED_TO_EXECUTE_RC -4323
#define VSDEL_HELP_UNIX_RC -4324
#define VSDELW_HELP_WIN_RC -4325
#define VSLM_DEMO_EXPIRED_RC -4326
#define DEMO_EXPIRATION_DATE_RC -4327
#define VSTRIAL_ERROR_IN_TRIAL_RC -4328
#define VSLM_PACKAGE_NOT_VALID_RC -4329
#define VSLM_SERIAL_AND_LICENSE_MISMATCH_RC -4330
#define VSLM_INVALID_PACKAGE_RC -4331
#define VSLM_TOO_MANY_PACKAGES_RC -4332
#define VSLM_PACKAGES_NOT_LICENSED_RC -4333
#define VSLM_USER_NOT_FOUND2_RC -4334
#define VSLM_PACKAGES_NOT_LICENSED2_RC -4335
#define VSLM_INVALID_PACKAGE2_RC -4336
#define VSREG_MACRO_NOT_FOUND_RC -4337
#define VSREG_ERROR_OPENING_DATA_FILE_RC -4338
#define VSREG_ERROR_READING_DATA_FILE_RC -4339
#define VSREG_INVALID_DATA_VERSION_RC -4340
#define VSTRIAL_INVALID_TRIAL_RC -4341
#define VSTRIAL_EXPIRING_RC -4342
#define VSTRIAL_MACRO_NOT_FOUND_RC -4343
#define VSTRIAL_TRIAL_EXPIRED_RC -4344
#define VSTRIAL_EXPIRING2_RC -4345
#define VSTRIAL_ECLIPSE_TRIAL_EXPIRED_RC -4346
#define VSTRIAL_ERROR_CONTACTING_REGISTRATION_SERVER_RC -4347
#define VSRC_DEMO_NAG_MESSAGE -4348
#define VSLM_UNABLE_TO_OBTAIN_FLEXLM_LICENSE_FROM_FILE_RC -4349
#define VSLM_UNABLE_TO_OBTAIN_LICENSE_RC -4350
#define VSLM_UNABLE_TO_RETURN_LICENSE_RC -4351
#define VSLM_UNABLE_TO_WRITE_BORROW_LICENSE_RC -4352
#define VSLM_UNABLE_TO_BORROW_LICENSE_RC -4353
#define VSLM_RETURN_FAILED_CHECKOUT_LICENSE_RC -4354
#define VSLM_BORROW_INCORRECT_LICENSE_RC -4355
#define VSLM_BORROW_FAILURE_RC -4356

///////////////////////////////////////////////////////////////////////////////
// XMLCFG
///////////////////////////////////////////////////////////////////////////////

#define VSRC_XMLCFG_EXPECTING_ROOT_ELEMENT_NAME -5400
#define VSRC_XMLCFG_EXPECTING_QUOTED_SYSTEM_ID -5401
#define VSRC_XMLCFG_STRING_NOT_TERMINATED -5402
#define VSRC_XMLCFG_NOT_USED1 -5403
#define VSRC_XMLCFG_START_TAG_NOT_TERMINATED -5404
#define VSRC_XMLCFG_COMMENT_NOT_TERMINATED -5405
#define VSRC_XMLCFG_INVALID_CHARACTERS_IN_COMMENT -5406
#define VSRC_XMLCFG_EXPECTING_AN_ELEMENT_NAME -5407
#define VSRC_XMLCFG_EXPECTING_ATTRIBUTE_NAME -5408
#define VSRC_XMLCFG_EXPECTING_EQUAL_AFTER_ATTRIBUTE_NAME -5409
#define VSRC_XMLCFG_ATTRIBUTE_VALUE_MUST_BE_QUOTED -5410
#define VSRC_XMLCFG_PROCESSING_INSTRUCTION_NOT_TERMINATED -5411
#define VSRC_XMLCFG_INPUT_ENDED_BEFORE_ALL_TAGS_WERE_TERMINATED -5412
#define VSRC_XMLCFG_EXPECTING_QUOTED_PUBLIC_ID -5413
#define VSRC_XMLCFG_DOCTYPE_INTERNAL_SUBSET_NOT_TERMINATED -5414
#define VSRC_XMLCFG_INVALID_DOCUMENT_STRUCTURE -5414
#define VSRC_XMLCFG_EXPECTING_SYSTEM_OR_PUBLIC_ID -5416
#define VSRC_XMLCFG_EXPECTING_PROCESSOR_NAME -5417
#define VSRC_XMLCFG_FILE_ALREADY_OPEN -5418
#define VSRC_XMLCFG_XML_DECLARATION_NOT_TERMIANTED -5419
#define VSRC_XMLCFG_EXPECTING_COMMENT_OR_CDATA -5420
#define VSRC_XMLCFG_CDATA_NOT_TERMINATED -5421
#define VSRC_XMLCFG_ATTRIBUTE_NOT_FOUND -5422
#define VSRC_XMLCFG_NAME_NOT_FOUND -5423
#define VSRC_XMLCFG_CANT_ADD_CHILD_NODE_TO_ATTRIBUTE_NODE -5424
#define VSRC_XMLCFG_ATTRIBUTES_MUST_BE_THE_FIRST_CHILDREN -5425
#define VSRC_XMLCFG_CANT_ADD_SIBLING_TO_ROOT_NODE -5426
#define VSRC_XML_SYSTEM_FAILED_TO_INITIALIZE -5427
#define VSRC_XML_UNEXPECTED_PARSING_ERROR1 -5428
#define VSRC_XML_GENERAL_PARSING_ERROR -5429
#define VSRC_XML_UNEXPECTED_PARSING_ERROR -5430
#define VSRC_XML_INTERNAL_ERROR_PROC_INDEX_NOT_FOUND -5431
#define VSRC_XMLCFG_NO_CHILDREN_COPIED -5432
#define VSRC_XMLCFG_INVALID_HANDLE -5433
#define VSRC_XMLCFG_INVALID_NODE_INDEX -5434
#define VSRC_XMLCFG_TOO_MANY_END_TAGS -5435

///////////////////////////////////////////////////////////////////////////////
// DEBUGGER
///////////////////////////////////////////////////////////////////////////////

#define DEBUG_NOT_INITIALIZED_RC -5500
#define DEBUG_BREAKPOINT_NOT_FOUND_RC -5501
#define DEBUG_THREAD_NOT_SUSPENDED_RC -5502
#define DEBUG_INVALID_ID_RC -5503
#define DEBUG_INVALID_INDEX_RC -5504
#define DEBUG_BREAKPOINT_CONDITION_UNSUPPORTED_RC -5505
#define DEBUG_THREAD_WAITING_FOR_SUSPEND_RC -5506
#define DEBUG_THREAD_NOT_FOUND_RC -5507
#define DEBUG_CLASS_NOT_FOUND_RC -5508
#define DEBUG_FUNCTION_NOT_FOUND_RC -5509
#define DEBUG_FIELD_NOT_FOUND_RC -5510
#define DEBUG_BREAKPOINT_NOT_DISABLED_RC -5511
#define DEBUG_BREAKPOINT_ALREADY_EXISTS_RC -5512
#define DEBUG_PROGRAM_FINISHED_RC -5513
#define DEBUG_BREAKPOINT_LINE_NOT_FOUND_RC -5514
#define DEBUG_BREAKPOINT_NOT_ALLOWED_RC -5515
#define DEBUG_WATCH_NOT_ALLOWED_RC -5516
#define DEBUG_NO_DEBUG_INFORMATION_RC -5517
#define DEBUG_EXCEPTION_NOT_FOUND_RC -5518
#define DEBUG_THREAD_NO_FRAMES_RC -5519
#define DEBUG_WATCH_ALREADY_EXISTS_RC -5520
#define DEBUG_NO_CURRENT_THREAD_RC -5521
#define DEBUG_NO_MEMBERS_RC -5522
#define DEBUG_INSTRUCTION_NOT_FOUND_RC -5523
#define DEBUG_FILE_NOT_FOUND_RC -5524
#define DEBUG_FEATURE_NOT_IMPLEMENTED_RC -5525
#define DEBUG_INVALID_SESSION_ID_RC -5526
#define DEBUG_NOT_A_WATCHPOINT_RC -5527
#define DEBUG_INVALID_BREAKPOINT_TYPE_RC -5528
#define DEBUG_INVALID_WATCHPOINT_CONDITION_RC -5529
#define DEBUG_BREAKPOINTS_NOT_ENABLED_ON_STARTUP_RC -5530
#define DEBUG_FEATURE_REMOVED_RC -5531
#define DEBUG_CAN_NOT_RESUME_CORE_FILE_RC -5532
#define DEBUG_EXPR_EXPECTING_COLON_RC -5550
#define DEBUG_EXPR_GENERAL_ERROR_RC -5551
#define DEBUG_EXPR_INVALID_OPERATOR_RC -5552
#define DEBUG_EXPR_EXPECTING_CLOSE_PAREN_RC -5553
#define DEBUG_EXPR_DIVIDE_BY_ZERO_RC -5554
#define DEBUG_EXPR_EXPECTING_COMMA_RC -5555
#define DEBUG_EXPR_EXPECTING_CLOSE_BRACKET_RC -5556
#define DEBUG_EXPR_INVALID_CONDITION_RC -5557
#define DEBUG_EXPR_CANNOT_CAST_VOID_RC -5558
#define DEBUG_EXPR_CANNOT_CAST_BOOLEAN_RC -5559
#define DEBUG_EXPR_CANNOT_CAST_STRING_RC -5560
#define DEBUG_EXPR_CANNOT_CAST_OBJECT_RC -5561
#define DEBUG_EXPR_INCOMPATIBLE_TYPE_RC -5562
#define DEBUG_EXPR_LOSS_OF_PRECISION -5563
#define DEBUG_EXPR_LHS_NOT_CLASS_RC -5564
#define DEBUG_EXPR_RHS_INVALID_RC -5565
#define DEBUG_EXPR_CANNOT_CAST_FUNCTION_RC -5566
#define DEBUG_EXPR_CANNOT_CAST_ARRAY_RC -5567
#define DEBUG_EXPR_SYNTAX_ERROR_RC -5568
#define DEBUG_EXPR_CANNOT_FIND_CONTEXT_RC -5569
#define DEBUG_EXPR_SYMBOL_NOT_FOUND_RC -5570
#define DEBUG_EXPR_NOT_ARRAY_RC -5572
#define DEBUG_EXPR_INVALID_ARRAY_INDEX_RC -5573
#define DEBUG_EXPR_NOT_FUNCTION_RC -5574
#define DEBUG_EXPR_CANNOT_CALL_FUNCTION_RC -5575
#define DEBUG_EXPR_EXCEPTION_RC -5576
#define DEBUG_EXPR_INVALID_ARGUMENT_RC -5577
#define DEBUG_EXPR_WRONG_NUMBER_OF_ARGUMENTS_RC -5578
#define DEBUG_EXPR_ARGUMENT_MISMATCH_RC -5579
#define DEBUG_EXPR_NOT_CLASS_RC -5580
#define DEBUG_EXPR_CONTAINS_NEW_RC -5581
#define DEBUG_EXPR_EXPECTING_OBJECT_RC -5582
#define DEBUG_EXPR_TOO_MANY_LEVELS_RC -5583
#define DEBUG_EXPR_CANNOT_EVALUATE_RC -5584
#define DEBUG_EXPR_STATIC_METHOD_RC -5585
#define DEBUG_JDWP_INVALID_SIZE_ARGUMENT_RC -5600
#define DEBUG_JDWP_PAST_END_OF_PACKET_RC -5601
#define DEBUG_JDWP_INVALID_TAG_CONSTANT_RC -5602
#define DEBUG_JDWP_UNSUPPORTED_TAG_RC -5603
#define DEBUG_JDWP_INVALID_HANDSHAKE_RC -5604
#define DEBUG_JDWP_UNSUPPORTED_BY_VIRTUAL_MACHINE_RC -5605
#define DEBUG_JDWP_INVALID_PACKET_SIZE_RC -5606
#define DEBUG_JDWP_INVALID_ARRAY_SIZE_RC -5607
#define DEBUG_JDWP_ERROR_MODIFYING_VARIABLE_RC -5608
#define DEBUG_JDWP_WATCHPOINT_NOT_SUPPORTED_RC -5609
#define DEBUG_JDWP_LOCAL_WATCHPOINT_NOT_SUPPORTED_RC -5610
#define DEBUG_DBGP_INVALID_PACKET_SIZE_RC -5650
#define DEBUG_DBGP_NO_MORE_DATA_RC -5651
#define DEBUG_DBGP_ALREADY_CONNECTED_RC -5652
#define DEBUG_DBGP_UNEXPECTED_RC -5653
#define DEBUG_DBGP_NOT_CONNECTED_RC -5654
#define DEBUG_DBGP_VERSION_NOT_SUPPORTED_RC -5655
#define DEBUG_DBGP_COMMAND_NOT_SUPPORTED_RC -5656
#define DEBUG_GDB_EMPTY_REPLY_RC -5700
#define DEBUG_GDB_TIMEOUT_RC -5701
#define DEBUG_GDB_TERMINATED_RC -5702
#define DEBUG_GDB_APP_EXITED_RC -5703
#define DEBUG_GDB_INVALID_REPLY_RC -5704
#define DEBUG_GDB_ERROR_REPLY_RC -5705
#define DEBUG_GDB_THREAD_OPERATION_UNSUPPORTED_RC -5706
#define DEBUG_GDB_ERROR_OPENING_FILE_RC -5707
#define DEBUG_GDB_ERROR_SETTING_ARGS_RC -5708
#define DEBUG_GDB_ERROR_ATTACHING_RC -5709
#define DEBUG_GDB_ERROR_LISTING_THREADS_RC -5710
#define DEBUG_GDB_ERROR_SELECTING_THREAD_RC -5711
#define DEBUG_GDB_ERROR_SELECTING_FRAME_RC -5712
#define DEBUG_GDB_ERROR_LISTING_STACK_RC -5713
#define DEBUG_GDB_ERROR_LISTING_LOCALS_RC -5714
#define DEBUG_GDB_ERROR_LISTING_ARGUMENTS_RC -5715
#define DEBUG_GDB_ERROR_EVALUATING_EXPRESSION_RC -5716
#define DEBUG_GDB_ERROR_MODIFYING_VARIABLE_RC -5717
#define DEBUG_GDB_ERROR_CONTINUING_RC -5718
#define DEBUG_GDB_ERROR_RUNNING_RC -5719
#define DEBUG_GDB_ERROR_STEPPING_RC -5720
#define DEBUG_GDB_ERROR_INTERRUPT_RC -5721
#define DEBUG_GDB_ERROR_SETTING_BREAKPOINT_RC -5722
#define DEBUG_GDB_ERROR_DELETING_BREAKPOINT_RC -5723
#define DEBUG_GDB_ERROR_SUSPENDING_RC -5724
#define DEBUG_GDB_INVALID_HANDSHAKE_RC -5725
#define DEBUG_GDB_INVALID_PACKET_RC -5726
#define DEBUG_GDB_ERROR_DETACHING_RC -5727
#define DEBUG_GDB_ERROR_LISTING_REGISTERS_RC -5728
#define DEBUG_GDB_ERROR_LISTING_MEMORY_RC -5729
#define DEBUG_GDB_ALL_PTYS_IN_USE_RC -5730
#define DEBUG_GDB_CANNOT_OPEN_SLAVE_PTY_RC -5731
#define DEBUG_GDB_MISSING_GDB_RC -5732
#define DEBUG_GDB_ERROR_ATTACHING_REMOTE_RC -5733
#define DEBUG_GDB_ERROR_ATTACHING_CORE_RC -5734
#define DEBUG_GDB_ERROR_STARTING_PROXY_RC -5735
#define DEBUG_GDB_PROXY_NOT_RUNNING_RC -5736
#define DEBUG_GDB_PROXY_ERROR_SENDING_RC -5737
#define DEBUG_GDB_PROXY_WINDOW_NOT_FOUND_RC -5738
#define DEBUG_GDB_PROXY_NOT_FOUND_RC -5739
#define DEBUG_GDB_ERROR_LISTING_DISASSEMBLY_RC -5740
#define DEBUG_GDB_TRUNCATED_VALUE_RC -5741
#define DEBUG_GDB_EXIT_REPLY_RC -5742
#define DEBUG_DOTNET_NO_PROCESS_RC -5800
#define DEBUG_DOTNET_ERROR_LISTING_THREADS_RC -5801
#define DEBUG_DOTNET_ERROR_LISTING_STACK_RC -5802
#define DEBUG_DOTNET_NO_CURRENT_MANAGED_FRAME_RC -5803
#define DEBUG_DOTNET_ERROR_GETTING_VARIABLES_RC -5804
#define DEBUG_DOTNET_ERROR_GETTING_CODE_RC -5805
#define DEBUG_DOTNET_ERROR_GETTING_FUNCITON_RC -5806
#define DEBUG_DOTNET_ERROR_GETTING_LINE_RC -5807
#define DEBUG_DOTNET_COULD_NOT_START_DEBUGGEE_RC -5808
#define DEBUG_DOTNET_PDB_FILE_OUT_OF_DATE_RC -5809
#define DEBUG_DOTNET_NOT_AN_ARRAY_RC -5810
#define DEBUG_DOTNET_CORDBG_E_FUNCTION_NOT_IL_RC -5811
#define DEBUG_DOTNET_CORDBG_E_UNRECOVERABLE_ERROR_RC -5812
#define DEBUG_DOTNET_CORDBG_E_PROCESS_TERMINATED_RC -5813
#define DEBUG_DOTNET_CORDBG_E_PROCESS_NOT_SYNCHRONIZED_RC -5814
#define DEBUG_DOTNET_CORDBG_E_CLASS_NOT_LOADED_RC -5815
#define DEBUG_DOTNET_CORDBG_E_IL_VAR_NOT_AVAILABLE_RC -5816
#define DEBUG_DOTNET_CORDBG_E_BAD_REFERENCE_VALUE_RC -5817
#define DEBUG_DOTNET_CORDBG_E_FIELD_NOT_AVAILABLE_RC -5818
#define DEBUG_DOTNET_CORDBG_E_VARIABLE_IS_ACTUALLY_LITERAL_RC -5819
#define DEBUG_DOTNET_CORDBG_E_NON_NATIVE_FRAME_RC -5820
#define DEBUG_DOTNET_CORDBG_E_NONCONTINUABLE_EXCEPTION_RC -5821
#define DEBUG_DOTNET_CORDBG_E_CODE_NOT_AVAILABLE_RC -5822
#define DEBUG_DOTNET_CORDBG_S_BAD_START_SEQUENCE_POINT_RC -5823
#define DEBUG_DOTNET_CORDBG_S_BAD_END_SEQUENCE_POINT_RC -5824
#define DEBUG_DOTNET_CORDBG_S_INSUFFICIENT_INFO_FOR_SET_IP_RC -5825
#define DEBUG_DOTNET_CORDBG_E_CANT_SET_IP_INTO_FINALLY_RC -5826
#define DEBUG_DOTNET_CORDBG_E_CANT_SET_IP_OUT_OF_FINALLY_RC -5827
#define DEBUG_DOTNET_CORDBG_E_CANT_SET_IP_INTO_CATCH_RC -5828
#define DEBUG_DOTNET_CORDBG_E_SET_IP_IMPOSSIBLE_RC -5829
#define DEBUG_DOTNET_CORDBG_E_SET_IP_NOT_ALLOWED_ON_NONLEAF_FRAME_RC -5830
#define DEBUG_DOTNET_CORDBG_E_FUNC_EVAL_BAD_START_POINT_RC -5831
#define DEBUG_DOTNET_CORDBG_E_INVALID_OBJECT_RC -5832
#define DEBUG_DOTNET_CORDBG_E_FUNC_EVAL_NOT_COMPLETE_RC -5833
#define DEBUG_DOTNET_CORDBG_S_FUNC_EVAL_HAS_NO_RESULT_RC -5834
#define DEBUG_DOTNET_CORDBG_S_VALUE_POINTS_TO_VOID_RC -5835
#define DEBUG_DOTNET_CORDBG_E_INPROC_NOT_IMPL_RC -5836
#define DEBUG_DOTNET_CORDBG_S_FUNC_EVAL_ABORTED_RC -5837
#define DEBUG_DOTNET_CORDBG_E_STATIC_VAR_NOT_AVAILABLE_RC -5838
#define DEBUG_DOTNET_CORDBG_E_OBJECT_IS_NOT_COPYABLE_VALUE_CLASS_RC -5839
#define DEBUG_DOTNET_CORDBG_E_CANT_SETIP_INTO_OR_OUT_OF_FILTER_RC -5840
#define DEBUG_DOTNET_CORDBG_E_CANT_CHANGE_JIT_SETTING_FOR_ZAP_MODULE_RC -5841
#define DEBUG_DOTNET_CORDBG_E_BAD_THREAD_STATE_RC -5842
#define DEBUG_DOTNET_CORDBG_E_DEBUGGING_NOT_POSSIBLE_RC -5843
#define DEBUG_DOTNET_CORDBG_E_KERNEL_DEBUGGER_ENABLED_RC -5844
#define DEBUG_DOTNET_CORDBG_E_KERNEL_DEBUGGER_PRESENT_RC -5845
#define DEBUG_DOTNET_CORDBG_E_INCOMPATIBLE_PROTOCOL_RC -5846
#define DEBUG_DOTNET_FIRST_CHANCE_EXCEPTION_RC -5847
#define DEBUG_DOTNET_UNEXPECTED_ERROR_RC -5848
#define DEBUG_DOTNET_UNHANDLED_EXCEPTION_RC -5849
#define DEBUG_DOTNET_PROCESS_NOT_RUNNING_RC -5850
#define DEBUG_DOTNET_THREAD_NO_LONGER_EXISTS_RC -5851
#define DEBUG_DOTNET_CREATE_STEPPER_FAILED_RC -5852
#define DEBUG_DOTNET_DEBUGGER_ALREADY_ATTACHED_RC -5853
#define DEBUG_CAPTION_SEPARATOR_RC -5900
#define DEBUG_CAPTION_VERIFIED_RC -5901
#define DEBUG_CAPTION_PREPARED_RC -5902
#define DEBUG_CAPTION_INITIALIZED_RC -5903
#define DEBUG_CAPTION_ERROR_RC -5904
#define DEBUG_CAPTION_UNKNOWN_RC -5905
#define DEBUG_CAPTION_MONITOR_RC -5906
#define DEBUG_CAPTION_RUNNING_RC -5907
#define DEBUG_CAPTION_SLEEPING_RC -5908
#define DEBUG_CAPTION_WAITING_RC -5909
#define DEBUG_CAPTION_ZOMBIE_RC -5910
#define DEBUG_CAPTION_SUSPENDED_RC -5911
#define DEBUG_CAPTION_ALIVE_RC -5912
#define DEBUG_CAPTION_DEFAULT_RC -5913
#define DEBUG_CAPTION_ITEM_RC -5914
#define DEBUG_CAPTION_ITEMS_RC -5915
#define DEBUG_CAPTION_NULL_RC -5916
#define DEBUG_CAPTION_TRUE_RC -5917
#define DEBUG_CAPTION_FALSE_RC -5918
#define DEBUG_CAPTION_VOID_RC -5919
#define DEBUG_CAPTION_CLASS_RC -5920
#define DEBUG_CAPTION_THROWN_RC -5921
#define DEBUG_CAPTION_CAUGHT_RC -5922
#define DEBUG_CAPTION_UNCAUGHT_RC -5923
#define DEBUG_CAPTION_IGNORE_RC -5924
#define DEBUG_CAPTION_CURR_TOP_OF_STACK_RC -5925
#define DEBUG_CAPTION_CURR_FRAME_OF_STACK_RC -5926
#define DEBUG_CAPTION_LAST_TOP_OF_STACK_RC -5927
#define DEBUG_CAPTION_LAST_FRAME_OF_STACK_RC -5928
#define DEBUG_CAPTION_BREAKPOINT_ENABLED_RC -5929
#define DEBUG_CAPTION_BREAKPOINT_DISABLED_RC -5930
#define DEBUG_CAPTION_FROZEN_RC -5931
#define DEBUG_CAPTION_UNDEFINED_VALUE_RC -5932
#define DEBUG_CAPTION_WATCHPOINT_ENABLED_RC -5933
#define DEBUG_CAPTION_WATCHPOINT_DISABLED_RC -5934

///////////////////////////////////////////////////////////////////////////////
// JDWP
///////////////////////////////////////////////////////////////////////////////

#define JDWP_ERROR_NONE_RC -6000
#define JDWP_ERROR_INVALID_THREAD_RC -6010
#define JDWP_ERROR_INVALID_THREAD_GROUP_RC -6011
#define JDWP_ERROR_INVALID_PRIORITY_RC -6012
#define JDWP_ERROR_THREAD_NOT_SUSPENDED_RC -6013
#define JDWP_ERROR_THREAD_SUSPENDED_RC -6014
#define JDWP_ERROR_INVALID_OBJECT_RC -6020
#define JDWP_ERROR_INVALID_CLASS_RC -6021
#define JDWP_ERROR_CLASS_NOT_PREPARED_RC -6022
#define JDWP_ERROR_INVALID_METHODID_RC -6023
#define JDWP_ERROR_INVALID_LOCATION_RC -6024
#define JDWP_ERROR_INVALID_FIELDID_RC -6025
#define JDWP_ERROR_INVALID_FRAMEID_RC -6030
#define JDWP_ERROR_NO_MORE_FRAMES_RC -6031
#define JDWP_ERROR_OPAQUE_FRAME_RC -6032
#define JDWP_ERROR_NOT_CURRENT_FRAME_RC -6033
#define JDWP_ERROR_TYPE_MISMATCH_RC -6034
#define JDWP_ERROR_INVALID_SLOT_RC -6035
#define JDWP_ERROR_DUPLICATE_RC -6040
#define JDWP_ERROR_NOT_FOUND_RC -6041
#define JDWP_ERROR_INVALID_MONITOR_RC -6050
#define JDWP_ERROR_NOT_MONITOR_OWNER_RC -6051
#define JDWP_ERROR_INTERRUPT_RC -6052
#define JDWP_ERROR_INVALID_CLASS_FORMAT_RC -6060
#define JDWP_ERROR_CIRCULAR_CLASS_DEFINITION_RC -6061
#define JDWP_ERROR_FAILS_VERIFICATION_RC -6062
#define JDWP_ERROR_ADD_METHOD_NOT_IMPLEMENTED_RC -6063
#define JDWP_ERROR_SCHEMA_CHANGE_NOT_IMPLEMENTED_RC -6064
#define JDWP_ERROR_INVALID_TYPESTATE_RC -6065
#define JDWP_ERROR_HIERARCHY_CHANGE_NOT_IMPLEMENTED_RC -6066
#define JDWP_ERROR_DELETE_METHOD_NOT_IMPLEMENTED_RC -6067
#define JDWP_ERROR_UNSUPPORTED_VERSION_RC -6068
#define JDWP_ERROR_NAMES_DONT_MATCH_RC -6069
#define JDWP_ERROR_CLASS_MODIFIERS_CHANGE_NOT_IMPLEMENTED_RC -6070
#define JDWP_ERROR_METHOD_MODIFIERS_CHANGE_NOT_IMPLEMENTED_RC -6071
#define JDWP_ERROR_NOT_IMPLEMENTED_RC -6099
#define JDWP_ERROR_NULL_POINTER_RC -6100
#define JDWP_ERROR_ABSENT_INFORMATION_RC -6101
#define JDWP_ERROR_INVALID_EVENT_TYPE_RC -6102
#define JDWP_ERROR_ILLEGAL_ARGUMENT_RC -6103
#define JDWP_ERROR_OUT_OF_MEMORY_RC -6110
#define JDWP_ERROR_ACCESS_DENIED_RC -6111
#define JDWP_ERROR_VM_DEAD_RC -6112
#define JDWP_ERROR_INTERNAL_RC -6113
#define JDWP_ERROR_UNATTACHED_THREAD_RC -6115
#define JDWP_ERROR_INVALID_TAG_RC -6500
#define JDWP_ERROR_ALREADY_INVOKING_RC -6502
#define JDWP_ERROR_INVALID_INDEX_RC -6503
#define JDWP_ERROR_INVALID_LENGTH_RC -6504
#define JDWP_ERROR_INVALID_STRING_RC -6506
#define JDWP_ERROR_INVALID_CLASS_LOADER_RC -6507
#define JDWP_ERROR_INVALID_ARRAY_RC -6508
#define JDWP_ERROR_TRANSPORT_LOAD_RC -6509
#define JDWP_ERROR_TRANSPORT_INIT_RC -6510
#define JDWP_ERROR_NATIVE_METHOD_RC -6511
#define JDWP_ERROR_INVALID_COUNT_RC -6512
#define JDWP_ERROR_INVALID_COMMAND_SET_RC -6513
#define JDWP_ERROR_INVALID_COMMAND_RC -6514

///////////////////////////////////////////////////////////////////////////////
// CVS
///////////////////////////////////////////////////////////////////////////////

#define CVS_ERROR_NOT_LOGGED_IN -6600
#define CVS_ERROR_EXE_NOT_FOUND -6601
#define CVS_ERROR_CHECKOUT_FAILED_RC -6602

///////////////////////////////////////////////////////////////////////////////
// SUBVERSION
///////////////////////////////////////////////////////////////////////////////

#define SVN_COMMAND_RETURNED_ERROR_RC -6650
#define SVN_DIRECTORIES_NOT_SUPPORTED_RC -6651
#define SVN_FILE_NOT_CONTROLLED_RC -6652
#define SVN_APP_NAME_RC -6653
#define SVN_COULD_NOT_GET_LOG_INFO_RC -6654
#define SVN_ERROR_CHECKOUT_FAILED_RC -6655
#define SVN_ERROR_CANT_GET_PASSWORD -6656
#define SVN_OUTPUT_TOO_LARGE -6657
#define SVN_COMMAND_RETURNED_ERROR_FOR_PATH_RC -6658

///////////////////////////////////////////////////////////////////////////////
// SVC
///////////////////////////////////////////////////////////////////////////////

#define SVC_COULD_NOT_GET_VC_INTERFACE_RC -6670
#define SVC_VC_INTERFACE_NOT_AVAILABLE_RC -6671
#define SVC_COULD_NOT_GET_VC_FILE_INTERFACE_RC -6672
#define SVC_FILE_INTERFACE_NOT_AVAILABLE_RC -6673
#define SVC_FILE_NOT_FOUND_RC -6674
#define SVC_SYSTEM_NOT_SUPPORTED_RC -6675
#define SVC_ANNOTATIONS_NOT_AVAILABLE_RC -6676
#define SVC_COULD_NOT_GET_HISTORY_INFO -6677
#define SVC_COULD_NOT_GET_CURRENT_VERSION_FILE -6678
#define SVC_COULD_NOT_GET_CURRENT_LOCAL_VERSION_FILE -6679
#define SVC_CURRENT_VERSION_IS_MOST_RECENT -6680
#define SVC_COULD_NOT_GET_FILE_STATUS -6681
#define SVC_COULD_NOT_UPDATE_FILE -6682
#define SVC_COULD_NOT_REVERT_FILE -6683
#define SVC_COULD_NOT_EDIT_FILE -6684
#define SVC_CHANGELIST_FAILED -6685
#define SVC_COMMIT_FAILED -6686
#define SVC_COULD_NOT_FIND_VC_EXE -6687
#define SVC_COMMAND_NOT_AVAILABLE -6688
#define SVC_COULD_NOT_GET_OUT_OF_DATE_FILES -6689
#define SVC_COULD_NOT_GET_LOCALLY_MODIFIED_FILES -6690
#define SVC_COULD_NOT_GET_INFO -6691
#define SVC_COULD_NOT_COMPARE_FILE -6692
#define SVC_COULD_NOT_ADD_FILE -6693
#define SVC_COULD_NOT_DELETE_FILE -6694
#define SVC_COULD_NOT_RESOLVE_FILE -6695
#define SVC_COULD_NOT_LIST_URL -6696
#define SVC_COULD_NOT_PUSH_TO_REPOSITORY -6697
#define SVC_COULD_NOT_PULL_FROM_REPOSITORY -6698

///////////////////////////////////////////////////////////////////////////////
// UPDATE
///////////////////////////////////////////////////////////////////////////////

#define UPDATE_CANNOT_WRITE_FILE_RC -6800
#define UPDATE_GENERAL_COPY_ERROR_RC -6801
#define UPDATE_BACKUP_ERROR_RC -6802
#define UPDATE_COULD_NOT_CREATE_PATH_ERROR_RC -6803
#define UPDATE_UPDATING_FILES_RC -6804
#define UPDATE_COMPILING_FILES_RC -6805
#define UPDATE_FILE_DOES_NOT_EXIST_RC -6806
#define UPDATE_COULD_NOT_SERIALIZE_RC -6807
#define UPDATE_COULD_NOT_DECOMPRESS_VSAPI_RC -6808
#define UPDATE_COULD_NOT_FIND_UNINST_LIST_RC -6809
#define UPDATE_CANNOT_UPDATE_TRIAL_RC -6810
#define UPDATE_NETWORK_INSTALL_RC -6811
#define UPDATE_INSUFFICIENT_DISK_SPACE_RC -6812
#define UPDATE_FAILED_RC -6813
#define UPDATE_COMPLETE_RC -6814
#define UPDATE_PATH_DOES_NOT_EXIST_RC -6815
#define UPDATE_BAD_ECLIPSE_PATH -6816
#define UPDATE_COULD_NOT_UPDATE_ECLIPSE_FEATURE_RC -6817
#define UPDATE_COULD_NOT_UPDATE_ECLIPSE_EXTENSION_RC -6818
#define UPDATE_RESTART_ECLIPSE_EXTENSION_RC -6819
#define UPDATE_CANNOT_OPEN_FILE_RC -6820

///////////////////////////////////////////////////////////////////////////////
// FTP
///////////////////////////////////////////////////////////////////////////////

#define VSRC_FTP_BAD_RESPONSE -6851
#define VSRC_FTP_CONNECTION_DEAD -6852
#define VSRC_FTP_CANNOT_STAT -6853
#define VSRC_FTP_WAITING_FOR_REPLY -6854
#define VSRC_FTP_BAD_CONFIG -6855
#define VSRC_FTP_CANNOT_AUTHENTICATE -6856
#define VSRC_FTP_END_ERRORS -6899

///////////////////////////////////////////////////////////////////////////////
// DELTASAVE
///////////////////////////////////////////////////////////////////////////////

#define DS_COULD_NOT_CREATE_ARCHIVE_FILE_RC -6900
#define DS_ARCHIVE_FILE_NOT_OPEN_RC -6901
#define DS_SOURCE_FILENAME_NOT_SET_RC -6902
#define DS_VERSION_NOT_FOUND_RC -6903
#define DS_PRE_CALLBACK_FAILED_RC -6904
#define DS_POST_CALLBACK_FAILED_RC -6905
#define DS_FILE_MATCHED_RC -6906
#define DS_NOT_CURRENT_BUFFER_RC -6907
#define DS_COULD_NOT_OPEN_FILE_WITH_CODE_PAGE_RC -6908
#define DS_FILE_EXCLUDED_RC -6909

///////////////////////////////////////////////////////////////////////////////
// VSDIFF
///////////////////////////////////////////////////////////////////////////////

#define VSDIFF_USAGE_RC -7000
#define VSDIFF_FILE_NOT_FOUND_RC -7001
#define VSDIFF_NO_MORE_DIFFERENCES_RC -7002
#define VSDIFF_NO_MORE_CONFLICTS_RC -7003
#define VSDIFF_APP_NAME -7004
#define VSDIFF_NO_MORE_DIFFERENCES_CLOSE_RC -7005
#define VSDIFF_TIMED_OUT_RC -7006

///////////////////////////////////////////////////////////////////////////////
// VSMERGE
///////////////////////////////////////////////////////////////////////////////

#define VSMERGE_USAGE_RC -7100
#define VSMERGE_FILE_NOT_FOUND_RC -7101
#define VSMERGE_APP_NAME -7102
#define VSMERGE_INVALID_OPTION_RC -7103

///////////////////////////////////////////////////////////////////////////////
// VSMFUNDO
///////////////////////////////////////////////////////////////////////////////

#define VSRC_MFUNDO_STACK_EMPTY -7200
#define VSRC_MFUNDO_STEP_ALREADY_ENDED -7201
#define VSRC_MFUNDO_END_STEP_NOT_CALLED -7202
#define VSRC_FAILED_TO_GENERATE_REDO_INFO -7203
#define VSRC_MFUNDO_BEGIN_NOT_CALLED -7204
#define VSRC_MFUNDO_BEGIN_STEP_NOT_CALLED -7205

///////////////////////////////////////////////////////////////////////////////
// VSREFACTOR
///////////////////////////////////////////////////////////////////////////////

#define VSRC_VSREFACTOR_CONFIGURATION_NOT_FOUND_1A -7500
#define VSRC_VSREFACTOR_CONFIGURATION_FILE_NOT_OPEN -7501
#define VSRC_VSREFACTOR_TRANSACTION_HANDLE_INVALID -7502
#define VSRC_VSREFACTOR_INTERNAL_ERROR -7503
#define VSRC_VSREFACTOR_SYMBOL_NOT_FOUND_1A -7504
#define VSRC_VSREFACTOR_INVALID_SYMBOL_1A -7505
#define VSRC_VSREFACTOR_INVALID_INCLUDE_PATH -7506
#define VSRC_VSREFACTOR_INVALID_DEFINE -7507
#define VSRC_VSREFACTOR_INVALID_CONFIGURATION_FILE -7508
#define VSRC_VSREFACTOR_STATIC_TO_INSTANCE_METHOD_WARNING -7509
#define VSRC_VSREFACTOR_CANNOT_REPLACE_CODE_WITH_CALL -7510
#define VSRC_VSREFACTOR_CANNOT_REPLACE_CODE_WITH_CONSTRUCTOR -7511
#define VSRC_VSREFACTOR_CANNOT_REPLACE_CODE_WITH_GOTO -7512
#define VSRC_VSREFACTOR_CANNOT_REPLACE_CODE_WITH_RETURN -7513
#define VSRC_VSREFACTOR_CANNOT_REPLACE_CODE_WITH_BREAK -7514
#define VSRC_VSREFACTOR_CANNOT_REPLACE_CODE_WITH_CONTINUE -7515
#define VSRC_VSREFACTOR_PARSING_FAILURE_1A -7516
#define VSRC_VSREFACTOR_PLEASE_WAIT -7517
#define VSRC_VSREFACTOR_ANALYZING -7518
#define VSRC_VSREFACTOR_PROCESSING_TEMPLATES -7519
#define VSRC_VSREFACTOR_PARSING -7520
#define VSRC_VSREFACTOR_FILE_1A -7521
#define VSRC_VSREFACTOR_FILE_3A -7522
#define VSRC_VSREFACTOR_REFACTORING -7523
#define VSRC_VSREFACTOR_FINDING_MODIFIED -7524
#define VSRC_VSREFACTOR_SAVING -7525
#define VSRC_VSREFACTOR_CLEANING_UP -7526
#define VSRC_VSREFACTOR_SYMBOL_IS_NOT_A_CLASS -7527
#define VSRC_VSREFACTOR_CLASS_DEFINITION_FILE_DOES_NOT_EXIST -7528
#define VSRC_VSREFACTOR_SYMBOL_ALREADY_DEFINED_1A -7529
#define VSRC_VSREFACTOR_SYMBOL_IS_NOT_A_FUNCTION_1A -7530
#define VSRC_VSREFACTOR_FUNCTION_CONFLICT -7531
#define VSRC_VSREFACTOR_NEW_PARAMETER_CONFLICT -7532
#define VSRC_VSREFACTOR_NOT_A_CLASS_MEMBER -7533
#define VSRC_VSREFACTOR_SYMBOL_WOULD_BE_HIDDEN_1A -7534
#define VSRC_VSREFACTOR_PREPROCESSING -7535
#define VSRC_VSREFACTOR_CONFIGURATION_UNEXPECTED_TYPE -7535
#define VSRC_VSREFACTOR_END_ERRORS -7999

///////////////////////////////////////////////////////////////////////////////
// VSPARSER
///////////////////////////////////////////////////////////////////////////////

#define VSRC_VSPARSER_ERROR_PREFIX -8000
#define VSRC_VSPARSER_SYNTAX_ERROR_1A -8001
#define VSRC_VSPARSER_EXPECTING_1A -8002
#define VSRC_VSPARSER_RECOVER_FAILED -8003
#define VSRC_VSPARSER_EXPECTING_IDENTIFIER -8004
#define VSRC_VSPARSER_EXPECTING_NEWLINE -8005
#define VSRC_VSPARSER_UNRECOGNIZED_CHARACTER -8006
#define VSRC_VSPARSER_UNTERMINATED_COMMENT -8007
#define VSRC_VSPARSER_UNTERMINATED_STRING -8008
#define VSRC_VSPARSER_MALFORMED_NUMBER -8009
#define VSRC_VSPARSER_UNEXPECTED_TOKEN_1A -8010
#define VSRC_VSPARSER_EXPECTING_NUMBER -8011
#define VSRC_VSPARSER_EXPECTING_ARGUMENT -8012
#define VSRC_VSPARSER_MISMATCHED_GROUP_2A -8013
#define VSRC_VSPARSER_UNRECOGNIZED_IDENTIFER_1A -8014
#define VSRC_VSPARSER_WARNING_PREFIX -8015
#define VSRC_VSPARSER_REUSE_OF_MACRO_PARAMETER_1A -8016
#define VSRC_VSPARSER_MACRO_REDEFINITION_1A -8017
#define VSRC_VSPARSER_SEE_PREVIOUS_DEFINITION_1A -8018
#define VSRC_VSPARSER_SEE_DEFINITION_1A -8019
#define VSRC_VSPARSER_SYMBOL_NOT_FOUND_1A -8020
#define VSRC_VSPARSER_INTERNAL_ERROR -8021
#define VSRC_VSPARSER_CANNOT_ADD_TWO_POINTERS -8022
#define VSRC_VSPARSER_NO_SUCH_OPERATOR_1A -8023
#define VSRC_VSPARSER_INCOMPLETE_EXPRESSION -8024
#define VSRC_VSPARSER_INVALID_ARRAY_INDEX -8025
#define VSRC_VSPARSER_INTEGRAL_TYPE_EXPECTED_1A -8026
#define VSRC_VSPARSER_EXPECTING_LVALUE -8027
#define VSRC_VSPARSER_CANNOT_ASSIGN_TO_2A -8028
#define VSRC_VSPARSER_LOSS_OF_PRECISION -8029
#define VSRC_VSPARSER_TYPES_ARE_INCOMPATIBLE -8030
#define VSRC_VSPARSER_EXPECTING_POINTER_TYPE -8031
#define VSRC_VSPARSER_UNEXPECTED_POINTER_TYPE -8032
#define VSRC_VSPARSER_EXPECTING_CLASS_TYPE -8033
#define VSRC_VSPARSER_DIVISION_BY_ZERO -8034
#define VSRC_VSPARSER_CANNOT_MODULO_FLOAT -8035
#define VSRC_VSPARSER_POINTER_TO_MEMBER_EXPECTED -8036
#define VSRC_VSPARSER_COULD_NOT_CALCULATE_SIZE -8037
#define VSRC_VSPARSER_EXPECTING_INTEGRAL_TYPE -8038
#define VSRC_VSPARSER_EXPECTING_CONSTANT_EXPRESSION -8039
#define VSRC_VSPARSER_INITIALIZER_NOT_ALLOWED -8040
#define VSRC_VSPARSER_SYMBOL_ALREADY_DEFINED_1A -8041
#define VSRC_VSPARSER_REPEATED_QUALIFIER -8042
#define VSRC_VSPARSER_CANNOT_CONVERT_TYPE_2A -8043
#define VSRC_VSPARSER_FUNCTION_MUST_RETURN_VALUE -8044
#define VSRC_VSPARSER_THIS_NOT_ALLOWED -8045
#define VSRC_VSPARSER_EXPECTING_TEMPLATE -8046
#define VSRC_VSPARSER_INCOMPATIBLE_TEMPLATE_ARGUMENT_1A -8047
#define VSRC_VSPARSER_CANNOT_NEW_REFERENCE_TYPE -8048
#define VSRC_VSPARSER_EXPECTING_NAMESPACE_1A -8049
#define VSRC_VSPARSER_PRIVATE_MEMBER_1A -8050
#define VSRC_VSPARSER_PROTECTED_MEMBER_1A -8051
#define VSRC_VSPARSER_PURE_BUT_NOT_VIRTUAL -8052
#define VSRC_VSPARSER_INLINE_BUT_NOT_FUNCTION -8053
#define VSRC_VSPARSER_VIRTUAL_BUT_NOT_FUNCTION -8054
#define VSRC_VSPARSER_EXPLICIT_BUT_NOT_CONSTRUCTOR -8055
#define VSRC_VSPARSER_VIRTUAL_CONSTRUCTOR -8056
#define VSRC_VSPARSER_RETURN_TYPE_NOT_ALLOWED -8057
#define VSRC_VSPARSER_EXPECTING_STATIC_MEMBER_1A -8058
#define VSRC_VSPARSER_FUNCTION_CANNOT_RETURN_VALUE -8059
#define VSRC_VSPARSER_STATIC_AND_VIRTUAL -8060
#define VSRC_VSPARSER_INITIALIZER_LIST_NOT_ALLOWED_1A -8061
#define VSRC_VSPARSER_TOO_MANY_INITIALIZERS -8062
#define VSRC_VSPARSER_AMBIGUOUS_FUNCTION_CALL_1A -8063
#define VSRC_VSPARSER_FUNCTION_WRONG_NUMBER_ARGUMENTS_2A -8064
#define VSRC_VSPARSER_TOO_MANY_ARGUMENTS -8065
#define VSRC_VSPARSER_NO_DEFAULT_ARGUMENT -8066
#define VSRC_VSPARSER_ARGUMENT_LISTS_DO_NOT_MATCH -8067
#define VSRC_VSPARSER_TEMPLATE_WRONG_NUMBER_ARGUMENTS_2A -8068
#define VSRC_VSPARSER_TEMPLATE_INSTANTIATED_BEFORE_SPECIALIZATION_1A -8069
#define VSRC_VSPARSER_TEMPLATE_INSTANTIATED_WITH_FORWARD_DECLARED_TYPE_1A -8070
#define VSRC_VSPARSER_TEMPLATE_UNABLE_TO_DETERMINE_ARGUMENTS_2A -8071
#define VSRC_VSPARSER_RECURSIVELY_INCLUDED_HEADER_FILE_1A -8072
#define VSRC_VSPARSER_SWITCH_HAS_MORE_THAN_ONE_DEFAULT -8073
#define VSRC_VSPARSER_INCOMPLETE_TYPE_INFO -8074
#define VSRC_VSPARSER_LINE_COMMENT_HAS_CONTINUATION -8075
#define VSRC_VSPARSER_NOT_A_MEMBER_OF_2A -8076
#define VSRC_VSPARSER_SWITCH_HAS_NO_CASE_OR_DEFAULT -8077
#define VSRC_VSPARSER_INTERNAL_ERROR_2A -8078
#define VSRC_VSPARSER_PREPROCESSING_LOCATION -8079
#define VSRC_VSPARSER_DEFAULT_VALUE_REDEFINITION_1A -8080
#define VSRC_VSPARSER_TRY_REQUIRES_HANDLER -8081
#define VSRC_VSPARSER_POINTER_ARITHMETIC_REQUIRES_INTEGRAL_TYPE -8082
#define VSRC_VSPARSER_TEMPLATE_PARAMETER_AMBIGUOUS_2A -8083
#define VSRC_VSPARSER_VARIABLE_LENGTH_ARRAYS_NOT_ALLOWED_HERE -8084
#define VSRC_VSPARSER_VOID_ILLEGALLY_USED_AS_ARGUMENT_TYPE -8085
#define VSRC_VSPARSER_CANNOT_ASSIGN_TO_CONST_2A -8086
#define VSRC_VSPARSER_MUTABLE_AND_CONST -8087
#define VSRC_VSPARSER_CANNOT_INCREMENT_CONST_1A -8088
#define VSRC_VSPARSER_CANNOT_USE_CONST_OR_VOLATILE_OUTSIDE_OF_CLASS -8089
#define VSRC_VSPARSER_END_ERRORS -8999

///////////////////////////////////////////////////////////////////////////////
// UPCHECK
///////////////////////////////////////////////////////////////////////////////

#define VSRC_UPCHECK_HELP -9000
#define VSRC_UPCHECK_UNKNOWN_COMMAND -9001
#define VSRC_UPCHECK_INVALID_ARGUMENT -9002
#define VSRC_UPCHECK_ERROR_OPENING_OUTPUT_FILE -9003
#define VSRC_UPCHECK_NOT_ENOUGH_ARGUMENTS -9004
#define VSRC_UPCHECK_ACTION_FAILED -9005
#define VSRC_UPCHECK_MISSING_ACTION_STATUS -9006
#define VSRC_UPCHECK_NOT_FOUND -9007
#define VSRC_UPCHECK_ERROR_STARTING -9008
#define VSRC_UPCHECK_TIMED_OUT -9009
#define VSRC_UPCHECK_INVALID_RESPONSE -9010
#define VSRC_UPCHECK_VERSION_NOT_SUPPORTED -9011
#define VSRC_UPCHECK_ERROR_CREATING_LOG -9012
#define VSRC_UPCHECK_ERROR_SAVING_MANIFEST -9013
#define VSRC_UPCHECK_ERROR_RETRIEVING_UPDATES -9014
#define VSRC_UPCHECK_MANUAL_CHECK_HELP -9015

///////////////////////////////////////////////////////////////////////////////
// VSRTE
///////////////////////////////////////////////////////////////////////////////

#define RTE_CANT_LOAD_JVM_LIB -9100
#define RTE_CANT_FIND_CREATE_VM -9101
#define RTE_NO_JVM -9102
#define RTE_CANT_ATTACH -9103
#define RTE_CANT_CREATE_ENV -9104
#define RTE_CANT_FIND_COMPILER_CLASS -9105
#define RTE_CANT_FIND_CONSTRUCTOR -9106
#define RTE_CANT_INSTANTIATE_CLASS -9107
#define RTE_CANT_CREATE_JSTRING -9108
#define RTE_CANT_FIND_COMPILE_ID -9109
#define RTE_CANT_GET_ERRORS -9110
#define RTE_MESSAGE_TYPE -9111
#define RTE_INVALID_ARGS_FOR_OPTION -9112
#define RTE_END_ERRORS -9200

///////////////////////////////////////////////////////////////////////////////
// DBGP
///////////////////////////////////////////////////////////////////////////////

#define DBGP_ERROR_NONE_RC -9201
#define DBGP_ERROR_PARSE_RC -9203
#define DBGP_ERROR_DUPLICATE_ARGS_RC -9204
#define DBGP_ERROR_INVALID_OPTIONS_RC -9205
#define DBGP_ERROR_UNIMPLEMENTED_RC -9206
#define DBGP_ERROR_COMMAND_NOT_AVAILABLE_RC -9207
#define DBGP_ERROR_OPENING_FILE_RC -9208
#define DBGP_ERROR_STREAM_REDIRECT_FAILED_RC -9209
#define DBGP_ERROR_BREAKPOINT_NOT_SET_RC -9210
#define DBGP_ERROR_BREAKPOINT_NOT_SUPPORTED_RC -9211
#define DBGP_ERROR_BREAKPOINT_INVALID_RC -9212
#define DBGP_ERROR_BREAKPOINT_NO_CODE_RC -9213
#define DBGP_ERROR_BREAKPOINT_INVALID_STATE_RC -9214
#define DBGP_ERROR_BREAKPOINT_NOT_EXIST_RC -9215
#define DBGP_ERROR_EVAL_RC -9216
#define DBGP_ERROR_EXPR_RC -9217
#define DBGP_ERROR_INVALID_PROPERTY_RC -9218
#define DBGP_ERROR_INVALID_STACK_DEPTH_RC -9219
#define DBGP_ERROR_INVALID_CONTEXT_RC -9220
#define DBGP_ERROR_ENCODING_NOT_SUPPORTED_RC -9221
#define DBGP_ERROR_INTERNAL_EXCEPTION_RC -9222
#define DBGP_ERROR_UNKNOWN_RC -9223
#define DBGP_END_ERRORS -9300

///////////////////////////////////////////////////////////////////////////////
// MACRO
///////////////////////////////////////////////////////////////////////////////

#define VSRC_FCF_ELEMENTS_COMMAND_LINE -101100
#define VSRC_FCF_ELEMENTS_STATUS_LINE -101101
#define VSRC_FCF_ELEMENTS_SBCS_DBCS_SOURCE_WINDOWS -101102
#define VSRC_FCF_ELEMENTS_HEX_SOURCE_WINDOWS -101103
#define VSRC_FCF_ELEMENTS_UNICODE_SOURCE_WINDOWS -101104
#define VSRC_FCF_ELEMENTS_FILE_MANAGER_WINDOWS -101105
#define VSRC_FCF_ELEMENTS_PARAMETER_INFO -101106
#define VSRC_FCF_ELEMENTS_PARAMETER_INFO_FIXED -101107
#define VSRC_FCF_ELEMENTS_SELECTION_LIST -101108
#define VSRC_FCF_ELEMENTS_MENU -101109
#define VSRC_FCF_ELEMENTS_DIALOG -101110
#define VSRC_FCF_ELEMENTS_MDI_CHILD_ICON -101111
#define VSRC_FCF_ELEMENTS_MDI_CHILD_TITLE -101112
#define VSRC_FCF_ELEMENTS_DIFF_EDITOR_WINDOWS -101113
#define VSRC_FCF_ELEMENTS_MINIHTML_PROPORTIONAL -101114
#define VSRC_FCF_ELEMENTS_MINIHTML_FIXED -101115
#define VSRC_FCF_ELEMENTS_DOCUMENT_TABS -101116
#define VSRC_CFG_COMMENT -101120
#define VSRC_CFG_CURRENT_LINE -101121
#define VSRC_CFG_CURSOR -101122
#define VSRC_CFG_NOSAVE_LINE -101123
#define VSRC_CFG_INSERTED_LINE -101124
#define VSRC_CFG_KEYWORD -101125
#define VSRC_CFG_LINE_NUMBER -101126
#define VSRC_CFG_LINE_PREFIX_AREA -101127
#define VSRC_CFG_MESSAGE -101128
#define VSRC_CFG_MODIFIED_LINE -101129
#define VSRC_CFG_NUMBER -101130
#define VSRC_CFG_PREPROCESSOR -101131
#define VSRC_CFG_SELECTED_CURRENT_LINE -101132
#define VSRC_CFG_SELECTION -101133
#define VSRC_CFG_STATUS -101134
#define VSRC_CFG_STRING -101135
#define VSRC_CFG_WINDOW_TEXT -101136
#define VSRC_CFG_PUNCTUATION -101137
#define VSRC_CFG_LIBRARY_SYMBOL -101138
#define VSRC_CFG_OPERATOR -101139
#define VSRC_CFG_USER_DEFINED_SYMBOL -101140
#define VSRC_CFG_FUNCTION -101141
#define VSRC_CFG_FILENAME -101142
#define VSRC_CFG_HIGHLIGHT -101143
#define VSRC_CFG_ATTRIBUTE -101144
#define VSRC_CFG_UNKNOWN_XML_ELEMENT -101145
#define VSRC_CFG_XHTML_ELEMENT_IN_XSL -101146
#define VSRC_CFG_ACTIVE_TOOL_WINDOW_CAPTION -101147
#define VSRC_CFG_INACTIVE_TOOL_WINDOW_CAPTION -101148
#define VSRC_CFG_LINE_COMMENT -101149
#define VSRC_CFG_UNABLE_TO_OPEN_SYSTEM_COLOR_SCHEME -101150
#define VSRC_CFG_COLOR_SCHEME_MODIFIED -101151
#define VSRC_CFG_NO_ACTIVE_SCHEME_TO_RENAME -101152
#define VSRC_CFG_FILE_NOT_FOUND -101153
#define VSRC_CFG_ERROR_READING_FILE -101154
#define VSRC_CFG_CANNOT_FIND_USER_SCHEME -101155
#define VSRC_CFG_INVALID_SCHEME_NAME -101156
#define VSRC_CFG_SCHEME_ALREADY_EXISTS -101157
#define VSRC_CFG_UNABLE_TO_SAVE -101158
#define VSRC_CFG_NO_ACTIVE_SCHEME_TO_REMOVE -101159
#define VSRC_CFG_UNABLE_TO_REMOVE -101160
#define VSRC_CFG_CANNOT_REMOVE_SYSTEM_SCHEMES -101161
#define VSRC_CFG_REMOVE_SCHEME_CONFIRMATION -101162
#define VSRC_CFG_RENAME_SCHEME -101163
#define VSRC_CFG_RENAME_TO -101164
#define VSRC_CFG_RGB_VALUES_RANGE_WARNING -101165
#define VSRC_CFG_INVALID_COLOR -101166
#define VSRC_CFG_SPECIFY_COLOR_SCHEME_NAME -101167
#define VSRC_CFG_INVALID_COLOR_SCHEME_NAME -101168
#define VSRC_CFG_CANNOT_OVERWRITE_SYSTEM_SCHEME -101169
#define VSRC_CFG_OVERWRITE_SCHEME_CONFIRMATION -101170
#define VSRC_CFG_COLOR_SCHEME_INCOMPATIBLE -101171
#define VSRC_CFG_DOCUMENTATION_COMMENT -101172
#define VSRC_CFG_DOCUMENTATION_KEYWORD -101173
#define VSRC_CFG_DOCUMENTATION_PUNCTUATION -101174
#define VSRC_CFG_DOCUMENTATION_ATTRIBUTE -101175
#define VSRC_CFG_DOCUMENTATION_ATTR_VALUE -101176
#define VSRC_CFG_IDENTIFIER -101177
#define VSRC_CFG_FLOATING_NUMBER -101178
#define VSRC_CFG_HEX_NUMBER -101179
#define VSRC_CFG_SINGLE_QUOTED_STRING -101180
#define VSRC_CFG_BACKQUOTED_STRING -101181
#define VSRC_CFG_UNTERMINATED_STRING -101182
#define VSRC_CFG_INACTIVE_CODE -101183
#define VSRC_CFG_INACTIVE_KEYWORD -101184
#define VSRC_CFG_IMAGINARY_SPACE -101185
#define VSRC_CFG_INACTIVE_COMMENT -101186
#define VSRC_CFG_ERROR -101187
#define VSRC_FF_OTHER -101200
#define VSRC_FF_KEYWORD -101201
#define VSRC_FF_NUMBER -101202
#define VSRC_FF_STRING -101203
#define VSRC_FF_COMMENT -101204
#define VSRC_FF_PREPROCESSING -101205
#define VSRC_FF_LINE_NUMBER -101206
#define VSRC_FF_SYMBOL1 -101207
#define VSRC_FF_SYMBOL2 -101208
#define VSRC_FF_SYMBOL3 -101209
#define VSRC_FF_SYMBOL4 -101210
#define VSRC_FF_FUNCTION -101211
#define VSRC_FF_ATTRIBUTE -101212
#define VSRC_FF_NOT -101220
#define VSRC_FF_CHOOSE_DIRECTORY -101221
#define VSRC_FF_CURDIR_IS -101222
#define VSRC_FF_OF_SELECTED -101223
#define VSRC_FF_CANNOT_GENERATE_MACRO -101225
#define VSRC_FF_NO_FILES_SELECTED -101226
#define VSRC_FF_COULD_NOT_OPEN_WORKSPACE_FILE -101227
#define VSRC_FF_INVALID_SWITCH -101228
#define VSRC_FF_FILE_NOT_FOUND -101229
#define VSRC_FF_NO_FILES_SELECTED_READ_ONLY -101230
#define VSRC_FF_FOLLOWING_LINES_SKIPPED -101231
#define VSRC_FC_INVALID_FONT_SIZE -101250
#define VSRC_FC_TERMINAL_FONT_SIZE -101251
#define VSRC_FC_INVALID_FONT_NAME -101252
#define VSRC_FC_CHILD_WINDOWS_NOT_UPDATED -101253
#define VSRC_FC_MUST_EXIT_AND_RESTART -101254
#define VSRC_FC_CHANGE_FONT_IN_ALL_WINDOWS -101255
#define VSRC_CHARSET_WESTERN -101275
#define VSRC_CHARSET_DEFAULT -101276
#define VSRC_CHARSET_SYMBOL -101277
#define VSRC_CHARSET_SHIFTJIS -101278
#define VSRC_CHARSET_HANGEUL -101279
#define VSRC_CHARSET_GB2312 -101280
#define VSRC_CHARSET_CHINESEBIG5 -101281
#define VSRC_CHARSET_OEMDOS -101282
#define VSRC_CHARSET_JOHAB -101283
#define VSRC_CHARSET_HEBREW -101284
#define VSRC_CHARSET_ARABIC -101285
#define VSRC_CHARSET_GREEK -101286
#define VSRC_CHARSET_TURKISH -101287
#define VSRC_CHARSET_THAI -101288
#define VSRC_CHARSET_CENTRALEUROPEAN -101289
#define VSRC_CHARSET_CYRILLIC -101290
#define VSRC_CHARSET_MAC -101291
#define VSRC_CHARSET_BALTIC -101292
#define VSRC_CHARSET_VIETNAMESE -101293
#define VSRC_UPCHECK_INTERVAL_1DAY -101325
#define VSRC_UPCHECK_INTERVAL_1WEEK -101326
#define VSRC_UPCHECK_INTERVAL_NEVER -101327
#define VSRC_UPCHECK_INTERVAL_CUSTOM -101328
#define VSRC_ABOUT_WEBSITE -101340
#define VSRC_ABOUT_SUPPORT_PHONE -101341
#define VSRC_CAPTION_SERIAL_NUMBER -101343
#define VSRC_CAPTION_LICENSED_PACKAGES -101344
#define VSRC_CAPTION_WEBSITE -101345
#define VSRC_CAPTION_SUPPORT_PHONE -101346
#define VSRC_CAPTION_SUPPORT_EMAIL -101347
#define VSRC_CAPTION_EXPIRATION_DATE -101348
#define VSRC_CAPTION_EMULATION -101348
#define VSRC_CAPTION_INSTALLATION_DIRECTORY -101349
#define VSRC_CAPTION_CONFIGURATION_DIRECTORY -101350
#define VSRC_CAPTION_CONFIGURATION_DRIVE_USAGE -101351
#define VSRC_CAPTION_SPILL_FILE -101352
#define VSRC_CAPTION_SPILL_FILE_DIRECTORY_DRIVE_USAGE -101353
#define VSRC_CAPTION_BUILD_DATE -101354
#define VSRC_CAPTION_OPERATING_SYSTEM -101355
#define VSRC_CAPTION_OPERATING_SYSTEM_VERSION -101356
#define VSRC_CAPTION_VERSION -101357
#define VSRC_CAPTION_KERNEL_LEVEL -101358
#define VSRC_CAPTION_BUILD_VERSION -101359
#define VSRC_CAPTION_XSERVER_VENDOR -101360
#define VSRC_CAPTION_MEMORY_LOAD -101361
#define VSRC_CAPTION_PHYSICAL_MEMORY_USAGE -101362
#define VSRC_CAPTION_PAGE_FILE_USAGE -101363
#define VSRC_CAPTION_VIRTUAL_MEMORY_USAGE -101364
#define VSRC_CAPTION_DIRECTORY -101365
#define VSRC_CAPTION_FLEXLM_SERIAL_NUMBER -101366
#define VSRC_CFG_SPECIALCHARS -101367
#define VSRC_CFG_CURRENT_LINE_BOX -101368
#define VSRC_CFG_VERTICAL_COL_LINE -101369
#define VSRC_CFG_MARGINS_COL_LINE -101370
#define VSRC_CFG_TRUNCATION_COL_LINE -101371
#define VSRC_CFG_PREFIX_AREA_LINE -101372
#define VSRC_CFG_BLOCK_MATCHING -101373
#define VSRC_PUSHED_BOOKMARK_NAME -101374
#define VSRC_CFG_INC_SEARCH_CURRENT -101375
#define VSRC_CFG_INC_SEARCH_MATCH -101376
#define VSRC_CFG_HEX_MODE_COLOR -101377
#define VSRC_DYNAMIC_SURROUND_MESSAGE -101378
#define VSRC_DYNAMIC_SURROUND_NO_MORE_UP -101379
#define VSRC_DYNAMIC_SURROUND_NO_MORE_DOWN -101380
#define VSRC_CAPTION_NOFUSERS -101381
#define VSRC_CFG_SYMBOL_HIGHLIGHT -101382
#define VSRC_CAPTION_LICENSE_EXPIRATION -101383
#define VSRC_CAPTION_LICENSE_TO -101384
#define VSRC_CFG_MODIFIED_FILE_TAB -101385
#define VSRC_CAPTION_LICENSE_FILE -101386
#define VSRC_CAPTION_MEMORY -101387
#define VSRC_CFG_MODIFIED_ITEM -101388
#define VSRC_CAPTION_CURRENT_PROJECT_TYPE -101389
#define VSRC_CAPTION_CURRENT_LANGUAGE -101390
#define VSRC_CAPTION_SCREEN_RESOLUTION -101391
#define VSRC_CAPTION_SHELL_INFO -101392
#define VSRC_CAPTION_PROCESSOR_ARCH -101393
#define VSRC_CAPTION_LICENSE_SERVER -101394
#define VSRC_CAPTION_LICENSE_BORROW_EXPIRATION -101395
#define VSRC_COLOR_CATEGORY_EDITOR_CURSOR -101400
#define VSRC_COLOR_CATEGORY_EDITOR_TEXT -101401
#define VSRC_COLOR_CATEGORY_MISC -101402
#define VSRC_COLOR_CATEGORY_DIFF -101403
#define VSRC_COLOR_CATEGORY_HIGHLIGHTS -101404
#define VSRC_COLOR_CATEGORY_XML -101405
#define VSRC_COLOR_CATEGORY_EDITOR_COLUMNS -101406
#define VSRC_COLOR_CATEGORY_COMMENTS -101407
#define VSRC_COLOR_CATEGORY_STRINGS -101408
#define VSRC_COLOR_CATEGORY_NUMBERS -101409
#define VSRC_CFG_SELECTION_DESCRIPTION -101410
#define VSRC_CFG_WINDOW_TEXT_DESCRIPTION -101411
#define VSRC_CFG_CURRENT_LINE_DESCRIPTION -101412
#define VSRC_CFG_SELECTED_CURRENT_LINE_DESCRIPTION -101413
#define VSRC_CFG_MESSAGE_DESCRIPTION -101414
#define VSRC_CFG_STATUS_DESCRIPTION -101415
#define VSRC_CFG_CURSOR_DESCRIPTION -101416
#define VSRC_CFG_MODIFIED_LINE_DESCRIPTION -101417
#define VSRC_CFG_INSERTED_LINE_DESCRIPTION -101418
#define VSRC_CFG_KEYWORD_DESCRIPTION -101419
#define VSRC_CFG_LINE_NUMBER_DESCRIPTION -101420
#define VSRC_CFG_NUMBER_DESCRIPTION -101421
#define VSRC_CFG_STRING_DESCRIPTION -101422
#define VSRC_CFG_COMMENT_DESCRIPTION -101423
#define VSRC_CFG_PREPROCESSOR_DESCRIPTION -101424
#define VSRC_CFG_PUNCTUATION_DESCRIPTION -101425
#define VSRC_CFG_LIBRARY_SYMBOL_DESCRIPTION -101426
#define VSRC_CFG_OPERATOR_DESCRIPTION -101427
#define VSRC_CFG_USER_DEFINED_SYMBOL_DESCRIPTION -101428
#define VSRC_CFG_NOSAVE_LINE_DESCRIPTION -101429
#define VSRC_CFG_FUNCTION_DESCRIPTION -101430
#define VSRC_CFG_LINE_PREFIX_AREA_DESCRIPTION -101431
#define VSRC_CFG_FILENAME_DESCRIPTION -101432
#define VSRC_CFG_HIGHLIGHT_DESCRIPTION -101433
#define VSRC_CFG_ATTRIBUTE_DESCRIPTION -101434
#define VSRC_CFG_UNKNOWN_XML_ELEMENT_DESCRIPTION -101435
#define VSRC_CFG_XHTML_ELEMENT_IN_XSL_DESCRIPTION -101436
#define VSRC_CFG_SPECIALCHARS_DESCRIPTION -101437
#define VSRC_CFG_CURRENT_LINE_BOX_DESCRIPTION -101438
#define VSRC_CFG_VERTICAL_COL_LINE_DESCRIPTION -101439
#define VSRC_CFG_MARGINS_COL_LINE_DESCRIPTION -101440
#define VSRC_CFG_TRUNCATION_COL_LINE_DESCRIPTION -101441
#define VSRC_CFG_PREFIX_AREA_LINE_DESCRIPTION -101442
#define VSRC_CFG_BLOCK_MATCHING_DESCRIPTION -101443
#define VSRC_CFG_INC_SEARCH_CURRENT_DESCRIPTION -101444
#define VSRC_CFG_INC_SEARCH_MATCH_DESCRIPTION -101445
#define VSRC_CFG_HEX_MODE_COLOR_DESCRIPTION -101446
#define VSRC_CFG_SYMBOL_HIGHLIGHT_DESCRIPTION -101447
#define VSRC_CFG_LINE_COMMENT_DESCRIPTION -101449
#define VSRC_CFG_DOC_COMMENT_DESCRIPTION -101450
#define VSRC_CFG_DOCUMENTATION_KEYWORD_DESCRIPTION -101451
#define VSRC_CFG_DOCUMENTATION_PUNCTUATION_DESCRIPTION -101452
#define VSRC_CFG_DOCUMENTATION_ATTRIBUTE_DESCRIPTION -101453
#define VSRC_CFG_DOCUMENTATION_ATTR_VALUE_DESCRIPTION -101454
#define VSRC_CFG_FLOATING_NUMBER_DESCRIPTION -101455
#define VSRC_CFG_HEX_NUMBER_DESCRIPTION -101456
#define VSRC_CFG_SINGLE_QUOTED_STRING_DESCRIPTION -101457
#define VSRC_CFG_BACKQUOTED_STRING_DESCRIPTION -101458
#define VSRC_CFG_UNTERMINATED_STRING_DESCRIPTION -101459
#define VSRC_CFG_IDENTIFIER_DESCRIPTION -101460
#define VSRC_CFG_INACTIVE_CODE_DESCRIPTION -101461
#define VSRC_CFG_INACTIVE_KEYWORD_DESCRIPTION -101462
#define VSRC_CFG_IMAGINARY_SPACE_DESCRIPTION -101463
#define VSRC_CFG_INACTIVE_COMMENT_DESCRIPTION -101464
#define VSRC_CFG_MODIFIED_ITEM_DESCRIPTION -101465
#define VSRC_CFG_NAVHINT -101466
#define VSRC_CFG_NAVHINT_DESCRIPTION -101467
#define VSRC_CFG_XML_CHARACTER_REF -101468
#define VSRC_CFG_XML_CHARACTER_REF_DESCRIPTION -101469
#define VSRC_CFG_TAG_FILES_LOADING -101470
#define VSRC_CFG_TAG_FILES_NONE -101471
#define VSRC_CFG_TAG_FILES_COUNT -101472
#define VSRC_CFG_ERROR_DESCRIPTION -101473
#define VSRC_CODEHELP_TITLE_LOCALS -101475
#define VSRC_CODEHELP_TITLE_MEMBERS -101476
#define VSRC_CODEHELP_TITLE_IMPORTS -101477
#define VSRC_CODEHELP_TITLE_STATICS -101478
#define VSRC_CODEHELP_TITLE_BUFFER -101479
#define VSRC_CODEHELP_TITLE_GLOBALS -101480
#define VSRC_CODEHELP_TITLE_PACKAGES -101481
#define VSRC_CODEHELP_TITLE_CLASSES -101482
#define VSRC_CODEHELP_TITLE_PROPS -101483
#define VSRC_CODEHELP_TITLE_BUILTINS -101484
#define VSRC_CODEHELP_TITLE_PARAMS -101485
#define VSRC_CODEHELP_TITLE_CONTROLS -101486
#define VSRC_CODEHELP_TITLE_KEYWORDS -101487
#define VSRC_CODEHELP_TITLE_FUNCTIONS -101488
#define VSRC_CODEHELP_TITLE_PROCEDURES -101489
#define VSRC_CODEHELP_TITLE_VARIABLES -101490
#define VSRC_CODEHELP_TITLE_DEFINES -101491
#define VSRC_CODEHELP_TITLE_EXPRS -101492
#define VSRC_CFG_SEARCH_RESULT_TRUNCATED -101493
#define VSRC_CFG_SEARCH_RESULT_TRUNCATED_DESCRIPTION -101494
#define VSRC_COLOR_CATEGORY_MARKDOWN -101495
#define VSRC_CFG_MARKDOWN_HEADER -101496
#define VSRC_CFG_MARKDOWN_HEADER_DESCRIPTION -101497
#define VSRC_CFG_MARKDOWN_CODE -101498
#define VSRC_CFG_MARKDOWN_CODE_DESCRIPTION -101499
#define VSRC_CFG_MARKDOWN_BLOCKQUOTE -101500
#define VSRC_CFG_MARKDOWN_BLOCKQUOTE_DESCRIPTION -101501
#define VSRC_CFG_MARKDOWN_LINK -101502
#define VSRC_CFG_MARKDOWN_LINK_DESCRIPTION -101503
#define VSRC_CFG_DOCUMENT_TAB_ACTIVE -101504
#define VSRC_CFG_DOCUMENT_TAB_ACTIVE_DESCRIPTION -101505
#define VSRC_CFG_DOCUMENT_TAB_MODIFIED -101506
#define VSRC_CFG_DOCUMENT_TAB_MODIFIED_DESCRIPTION -101507
#define VSRC_CFG_DOCUMENT_TAB_SELECTED -101508
#define VSRC_CFG_DOCUMENT_TAB_SELECTED_DESCRIPTION -101509
#define VSRC_CFG_DOCUMENT_TAB_UNSELECTED -101510
#define VSRC_CFG_DOCUMENT_TAB_UNSELECTED_DESCRIPTION -101511

///////////////////////////////////////////////////////////////////////////////
// SCC
///////////////////////////////////////////////////////////////////////////////

#define VSSCC_ERROR_COULD_NOT_FIND_INSTALLED_PROVIDER_KEY_RC -102000
#define VSSCC_ERROR_COULD_NOT_FIND_SPECIFIC_PROVIDER_KEY_RC -102001
#define VSSCC_ERROR_COULD_NOT_FIND_SCCSERVERPATH_RC -102002
#define VSSCC_ERROR_COULD_NOT_LOAD_LIBRARY_RC -102003
#define VSSCC_ERROR_INIT_FAILED_RC -102004
#define VSSCC_ERROR_OPTION_NOT_SUPPORTED_RC -102005
#define VSSCC_ERROR_MAY_BE_32_BIT_DLL_RC -102008
#define VSSCC_WARN_ABOUT_32_BIT_SCC_SYSTEMS_RC -102009
#define VSSCC_E_INITIALIZEFAILED_RC -102020
#define VSSCC_E_UNKNOWNPROJECT_RC -102021
#define VSSCC_E_COULDNOTCREATEPROJECT_RC -102022
#define VSSCC_E_NOTCHECKEDOUT_RC -102023
#define VSSCC_E_ALREADYCHECKEDOUT_RC -102024
#define VSSCC_E_FILEISLOCKED_RC -102025
#define VSSCC_E_FILEOUTEXCLUSIVE_RC -102026
#define VSSCC_E_ACCESSFAILURE_RC -102027
#define VSSCC_E_CHECKINCONFLICT_RC -102028
#define VSSCC_E_FILEALREADYEXISTS_RC -102029
#define VSSCC_E_FILENOTCONTROLLED_RC -102030
#define VSSCC_E_FILEISCHECKEDOUT_RC -102031
#define VSSCC_E_NOSPECIFIEDVERSION_RC -102032
#define VSSCC_E_OPNOTSUPPORTED_RC -102033
#define VSSCC_E_NONSPECIFICERROR_RC -102034
#define VSSCC_E_OPNOTPERFORMED_RC -102035
#define VSSCC_E_TYPENOTSUPPORTED_RC -102036
#define VSSCC_E_VERIFYMERGE_RC -102037
#define VSSCC_E_FIXMERGE_RC -102038
#define VSSCC_E_SHELLFAILURE_RC -102039
#define VSSCC_E_INVALIDUSER_RC -102040
#define VSSCC_E_PROJECTALREADYOPEN_RC -102041
#define VSSCC_E_PROJSYNTAXERR_RC -102042
#define VSSCC_E_INVALIDFILEPATH_RC -102043
#define VSSCC_E_PROJNOTOPEN_RC -102044
#define VSSCC_E_NOTAUTHORIZED_RC -102045
#define VSSCC_E_FILESYNTAXERR_RC -102046
#define VSSCC_E_FILENOTEXIST_RC -102047

///////////////////////////////////////////////////////////////////////////////
// OEM
///////////////////////////////////////////////////////////////////////////////


#endif
