#!/bin/bash

rm /tmp/ext.txt

for fullpath in `find . -type f`
do
    filename="${fullpath##*/}"                      # Strip longest match of */ from start
    dir="${fullpath:0:${#fullpath} - ${#filename}}" # Substring from 0 thru pos of filename
    base="${filename%.[^.]*}"                       # Strip shortest match of . plus at least one non-dot char from end
    ext="${filename:${#base} + 1}"                  # Substring from len of base thru end
    if [[ -z "$base" && -n "$ext" ]]; then          # If we have an extension and no base, it's really the base
        base=".$ext"
        ext=""
    fi

    #echo -e "$fullpath:\n\tdir  = \"$dir\"\n\tbase = \"$base\"\n\text  = \"$ext\""
    echo -e "$ext"  >>  /tmp/ext.txt
done

cat /tmp/ext.txt | sort > /tmp/ext_sort.txt
cat /tmp/ext_sort.txt | uniq > /tmp/ext_uniq.txt
cat /tmp/ext_uniq.txt
