#ifndef VSMSGDEFS_GREP_H
#define VSMSGDEFS_GREP_H

enum VSMSGDEFS_GREP {
    GREP_USAGE_RC = -3600,
    GREP_EXECTING_TWO_FILENAMES_RC = -3625,
    GREP_EXPECTING_PATTERN_STRING_RC = -3626,
    GREP_PATTERN_STRING_ALREADY_SPECIFIED_RC = -3627,
    GREP_EXPECTING_FILENAME_RC = -3628,
    GREP_UNABLE_TO_OPEN_EXPRESSION_FILE_RC = -3629,
    GREP_MUST_SPECIFY_PATTERN_BEFORE_FILES_RC = -3630,
    GREP_UNKNOWN_OPTION_RC = -3631,
    GREP_UNABLED_OPEN_FILE_ABORT_RC = -3632,
    GREP_ERROR_READING_FILE_ABORT_RC = -3633,
    GREP_FILENAME_TOO_LONG_RC = -3634,
    GREP_UNABLED_OPEN_INPUT_FILE_RC = -3635,
    GREP_UNABLED_OPEN_OUTPUT_FILE_RC = -3636,
    GREP_UNABLE_TO_FIND_DEFAULT_OPTIONS_RC = -3637,
    GREP_UNABLE_TO_WRITE_TO_OUTPUT_FILE_RC = -3638,
    GREP_UNABLED_OPEN_FILE_SKIPPED_RC = -3639,
    GREP_INVALID_WORD_RE_RC = -3640,
    GREP_INVALID_RE_RC = -3641,
};

#endif
