#ifndef VSMSGDEFS_UPDATE_H
#define VSMSGDEFS_UPDATE_H

enum VSMSGDEFS_UPDATE {
    UPDATE_CANNOT_WRITE_FILE_RC = -6800,
    UPDATE_GENERAL_COPY_ERROR_RC = -6801,
    UPDATE_BACKUP_ERROR_RC = -6802,
    UPDATE_COULD_NOT_CREATE_PATH_ERROR_RC = -6803,
    UPDATE_UPDATING_FILES_RC = -6804,
    UPDATE_COMPILING_FILES_RC = -6805,
    UPDATE_FILE_DOES_NOT_EXIST_RC = -6806,
    UPDATE_COULD_NOT_SERIALIZE_RC = -6807,
    UPDATE_COULD_NOT_DECOMPRESS_VSAPI_RC = -6808,
    UPDATE_COULD_NOT_FIND_UNINST_LIST_RC = -6809,
    UPDATE_CANNOT_UPDATE_TRIAL_RC = -6810,
    UPDATE_NETWORK_INSTALL_RC = -6811,
    UPDATE_INSUFFICIENT_DISK_SPACE_RC = -6812,
    UPDATE_FAILED_RC = -6813,
    UPDATE_COMPLETE_RC = -6814,
    UPDATE_PATH_DOES_NOT_EXIST_RC = -6815,
    UPDATE_BAD_ECLIPSE_PATH = -6816,
    UPDATE_COULD_NOT_UPDATE_ECLIPSE_FEATURE_RC = -6817,
    UPDATE_COULD_NOT_UPDATE_ECLIPSE_EXTENSION_RC = -6818,
    UPDATE_RESTART_ECLIPSE_EXTENSION_RC = -6819,
    UPDATE_CANNOT_OPEN_FILE_RC = -6820,
};

#endif
