#ifndef VSMSGDEFS_CLEX_H
#define VSMSGDEFS_CLEX_H

enum VSMSGDEFS_CLEX {
    CLEX_NOT_ENOUGH_MEMORY_RC = -3547,
    CLEX_TOO_MANY_MLCOMMENTS_DEFINED_RC = -3548,
    CLEX_IDENTIFIER_MLCOMMENTS_NOT_SUPPORTED_RC = -3549,
    CLEX_TOO_MANY_CFLINECOMMENTS_DEFINED_RC = -3550,
    CLEX_IDCHARS_MUST_BE_DEFINED_FIRST_RC = -3551,
    CLEX_INVALID_STYLE_RC = -3552,
    CLEX_INVALID_MLCOMMENT_RC = -3553,
    CLEX_INVALID_LINECOMMENT_RC = -3554,
    CLEX_INVALID_NAME_RC = -3555,
    CLEX_FILE_NOT_FOUND_RC = -3556,
    CLEX_ACCESS_DENIED_RC = -3557,
    CLEX_UNABLE_TO_OPEN_FILE_RC = -3558,
    CLEX_INVALID_IDCHARS_RC = -3559,
    CLEX_NO_INFO_FOR_FILE_RC = -3560,
};

#endif
