#ifndef VSMSGDEFS_VSUPDATE_H
#define VSMSGDEFS_VSUPDATE_H

enum VSMSGDEFS_VSUPDATE {
    VSUPDATE_LICENSE_TRANSFERRED_RC = -350,
    VSUPDATE_HELP_RC = -351,
    VSUPDATE_INVALID_SERIAL_NUMBER_RC = -352,
    VSUPDATE_HELP_WIN_RC = -353,
    VSUPDATE_INVALID_LICENSE_RC = -354,
    VSUPDATE_INVALID_PACKS_RC = -355,
    VSUPDATE_INCORRECT_ARCHITECTURE_RC = -356,
    VSUPDATE_DLL_ONLY_FOR_WINDOWS_RC = -357,
};

#endif
