#ifndef VSMSGDEFS_CFORMAT_H
#define VSMSGDEFS_CFORMAT_H

enum VSMSGDEFS_CFORMAT {
    CFERROR_GENERAL_ERROR_RC = -200,
    CFERROR_EOF_UNEXPECTED_RC = -201,
    CFERROR_SYMBOL_UNEXPECTED_RC = -202,
    CFERROR_RIGHTPAREN_EXPECTED_RC = -203,
    CFERROR_RIGHTBRACE_EXPECTED_RC = -204,
    CFERROR_RIGHTBRACKET_EXPECTED_RC = -205,
    CFERROR_LEFTPAREN_EXPECTED_RC = -206,
    CFERROR_LEFTBRACE_EXPECTED_RC = -207,
    CFERROR_LEFTBRACKET_EXPECTED_RC = -208,
    CFERROR_RIGHTPAREN_UNEXPECTED_RC = -209,
    CFERROR_RIGHTBRACE_UNEXPECTED_RC = -210,
    CFERROR_RIGHTBRACKET_UNEXPECTED_RC = -211,
    CFERROR_LEFTPAREN_UNEXPECTED_RC = -212,
    CFERROR_LEFTBRACE_UNEXPECTED_RC = -213,
    CFERROR_LEFTBRACKET_UNEXPECTED_RC = -214,
    CFERROR_CASE_UNEXPECTED_RC = -215,
    CFERROR_COLON_EXPECTED_RC = -216,
    CFERROR_SEMI_EXPECTED_RC = -217,
    CFERROR_PP_UNEXPECTED_RC = -218,
    CFERROR_WHILE_EXPECTED_RC = -219,
    CFERROR_ELSE_UNEXPECTED_RC = -220,
    CFERROR_ERROR_IN_TEMPLATE_RC = -221,
    CFERROR_ENDSUBMENU_UNEXPECTED_RC = -222,
    CFERROR_SUBMENU_UNEXPECTED_RC = -223,
    CFERROR_MENU_UNEXPECTED_RC = -224,
    CFERROR_CATCH_UNEXPECTED_RC = -225,
    CFERROR_FINALLY_UNEXPECTED_RC = -226,
    CFERROR_UNHANDLED_SYNTAX_RC = -227,
};

#endif
