#ifndef VSMSGDEFS_VSDIFF_H
#define VSMSGDEFS_VSDIFF_H

enum VSMSGDEFS_VSDIFF {
    VSDIFF_USAGE_RC = -7000,
    VSDIFF_FILE_NOT_FOUND_RC = -7001,
    VSDIFF_NO_MORE_DIFFERENCES_RC = -7002,
    VSDIFF_NO_MORE_CONFLICTS_RC = -7003,
    VSDIFF_APP_NAME = -7004,
    VSDIFF_NO_MORE_DIFFERENCES_CLOSE_RC = -7005,
    VSDIFF_TIMED_OUT_RC = -7006,
};

#endif
