#ifndef VSMSGDEFS_OBJECT_H
#define VSMSGDEFS_OBJECT_H

enum VSMSGDEFS_OBJECT {
    OBJECT_FILE_INCOMPLETE_HEADER_RC = -4150,
    OBJECT_FILE_BAD_MAGIC_NUMBER_RC = -4151,
    OBJECT_FILE_UNRECOGNIZED_RC = -4152,
    OBJECT_FILE_NO_DEBUG_RC = -4153,
};

#endif
