#ifndef VSMSGDEFS_SLICKC_COMPILER_H
#define VSMSGDEFS_SLICKC_COMPILER_H

enum VSMSGDEFS_SLICKC_COMPILER {
    SCCOMPERR_FILEPOS = -5000,
    SCCOMPERR_SPACEFILEPOS = -5001,
    SCCOMPERR_ERROR = -5002,
    SCCOMPERR_WARNING = -5003,
    SCCOMPERR_FATALERROR = -5004,
    SCCOMPERR_DEFINE_NOT_INITIALIZED = -5005,
    SCCOMPERR_ID_TOO_LONG = -5006,
    SCCOMPERR_COMMENT_NOT_TERMINATED = -5006,
    SCCOMPERR_ILLEGAL_CHARACTER = -5007,
    SCCOMPERR_STRING_NOT_TERMINATED = -5008,
    SCCOMPERR_INVALID_STRING_TOKEN = -5009,
    SCCOMPERR_UNRECOGNIZED_ESCAPE_SEQUENCE = -5010,
    SCCOMPERR_EMPTY_CHARACTER_LITERAL = -5011,
    SCCOMPERR_SINGLE_LINE_COMMENT_OR_EOF_EXPECTED = -5012,
    SCCOMPERR_UNRECOGNIZED_PREPROCESSOR_DIRECTIVE = -5013,
    SCCOMPERR_PREPROCESSING_NESTED_TOO_DEEP = -5014,
    SCCOMPERR_UNEXPECTED_PREPROCESSOR_DIRECTIVE = -5015,
    SCCOMPERR_RIGHT_PAREN_EXPECTED = -5016,
    SCCOMPERR_INVALID_PREPROCESSOR_EXPRESSION = -5017,
    SCCOMPERR_ERROR_DIRECTIVE = -5018,
    SCCOMPERR_IDENTIFIER_EXPECTED = -5019,
};

#endif
