#ifndef VSMSGDEFS_REGEX_H
#define VSMSGDEFS_REGEX_H

enum VSMSGDEFS_REGEX {
    INVALID_REGULAR_EXPRESSION_RC = -2500,
    EOL1_RC = -2501,
    EOL2_RC = -2502,
    RE_EOF_RC = -2503,
    REBREAK_KEY_PRESSED_RC = -2504,
};

#endif
