#ifndef VSMSGDEFS_SVC_H
#define VSMSGDEFS_SVC_H

enum VSMSGDEFS_SVC {
    SVC_COULD_NOT_GET_VC_INTERFACE_RC = -6670,
    SVC_VC_INTERFACE_NOT_AVAILABLE_RC = -6671,
    SVC_COULD_NOT_GET_VC_FILE_INTERFACE_RC = -6672,
    SVC_FILE_INTERFACE_NOT_AVAILABLE_RC = -6673,
    SVC_FILE_NOT_FOUND_RC = -6674,
    SVC_SYSTEM_NOT_SUPPORTED_RC = -6675,
    SVC_ANNOTATIONS_NOT_AVAILABLE_RC = -6676,
    SVC_COULD_NOT_GET_HISTORY_INFO = -6677,
    SVC_COULD_NOT_GET_CURRENT_VERSION_FILE = -6678,
    SVC_COULD_NOT_GET_CURRENT_LOCAL_VERSION_FILE = -6679,
    SVC_CURRENT_VERSION_IS_MOST_RECENT = -6680,
    SVC_COULD_NOT_GET_FILE_STATUS = -6681,
    SVC_COULD_NOT_UPDATE_FILE = -6682,
    SVC_COULD_NOT_REVERT_FILE = -6683,
    SVC_COULD_NOT_EDIT_FILE = -6684,
    SVC_CHANGELIST_FAILED = -6685,
    SVC_COMMIT_FAILED = -6686,
    SVC_COULD_NOT_FIND_VC_EXE = -6687,
    SVC_COMMAND_NOT_AVAILABLE = -6688,
    SVC_COULD_NOT_GET_OUT_OF_DATE_FILES = -6689,
    SVC_COULD_NOT_GET_LOCALLY_MODIFIED_FILES = -6690,
    SVC_COULD_NOT_GET_INFO = -6691,
    SVC_COULD_NOT_COMPARE_FILE = -6692,
    SVC_COULD_NOT_ADD_FILE = -6693,
    SVC_COULD_NOT_DELETE_FILE = -6694,
    SVC_COULD_NOT_RESOLVE_FILE = -6695,
    SVC_COULD_NOT_LIST_URL = -6696,
    SVC_COULD_NOT_PUSH_TO_REPOSITORY = -6697,
    SVC_COULD_NOT_PULL_FROM_REPOSITORY = -6698,
};

#endif
