#ifndef VSMSGDEFS_BSC_H
#define VSMSGDEFS_BSC_H

enum VSMSGDEFS_BSC {
    BSC_INCORRECT_EXTENSION_RC = -4100,
    BSC_ERROR_OPENING_FILE_RC = -4101,
    BSC_NO_INSTANCES_RC = -4102,
    BSC_ONLY_ON_WINDOWS_RC = -4103,
    BSC_CANNOT_OPEN_DLL_RC = -4104,
};

#endif
