#ifndef VSMSGDEFS_VSUNINST_H
#define VSMSGDEFS_VSUNINST_H

enum VSMSGDEFS_VSUNINST {
    VSUNINST_TITLE_INSTALL_FAILED_RC = -550,
    VSUNINST_WIN31_NOT_SUPPORTED_RC = -551,
    VSUNINST_FOLDER_TOO_SHORT_RC = -552,
    VSUNINST_ARE_YOU_SURE_RC = -553,
    VSUNINST_UNINSTALL_COMPLETED_RC = -554,
    VSUNINST_UNINSTALL_COMPLETED2_RC = -555,
    VSUNINST_BAD_ARGUMENT_RC = -556,
    VSUNINST_TEMP_DIRECTORY_NOT_FOUND_RC = -557,
    VSUNINST_UNABLE_TO_CREATE_TEMP_FILE_RC = -558,
    VSUNINST_ERROR_WRITING_TO_FILE_RC = -559,
    VSUNINST_FAILED_TO_EXECUTE_RC = -560,
};

#endif
