#ifndef VSMSGDEFS_VSPROXY_H
#define VSMSGDEFS_VSPROXY_H

enum VSMSGDEFS_VSPROXY {
    VSPROXY_CMDLINE_TOO_LONG_RC = -150,
    VSPROXY_BROKEN_PIPE_RC = -151,
    VSPROXY_BAD_PIPE_RC = -152,
    VSPROXY_INVALID_HANDLE_RC = -153,
    VSPROXY_INVALID_COMMAND_RC = -154,
    VSPROXY_NOT_ENOUGH_ARGUMENTS_RC = -155,
    VSPROXY_ALREADY_TRANSFERRING_DATA_RC = -156,
    VSPROXY_BAD_FILE_HANDLE_RC = -157,
    VSPROXY_NO_TRANSFER_SOURCEDEST_RC = -158,
    VSPROXY_NOT_TRANSFERRING_DATA_RC = -159,
    VSPROXY_STILL_TRANSFERRING_DATA_RC = -160,
};

#endif
