#ifndef VSMSGDEFS_JAVA_H
#define VSMSGDEFS_JAVA_H

enum VSMSGDEFS_JAVA {
    JAVA_CLASS_INCOMPLETE_HEADER_RC = -4125,
    JAVA_CLASS_BAD_MAGIC_NUMBER_RC = -4126,
    JAVA_CLASS_UNSUPPORTED_VERSION_RC = -4127,
    JAVA_CLASS_UNKNOWN_CONSTANT_TYPE_RC = -4128,
    JAVA_CLASS_ATTRIBUTE_LENGTH_MISMATCH_RC = -4129,
    JAVA_CLASS_SOURCE_NOT_FOUND_RC = -4130,
    JAVA_CLASS_INVALID_CONSTANT_INDEX_RC = -4131,
    JAVA_CLASS_STRING_NOT_FOUND_RC = -4132,
    JAVA_JAR_INCOMPLETE_HEADER_RC = -4133,
    JAVA_JAR_BAD_MAGIC_NUMBER_RC = -4134,
    JAVA_JAR_UNSUPPORTED_VERSION_RC = -4135,
    JAVA_JAR_DECOMPRESS_ERROR_RC = -4136,
    JAVA_JAR_CORRUPT_HEADER_RC = -4137,
};

#endif
