#ifndef VSMSGDEFS_METADATA_H
#define VSMSGDEFS_METADATA_H

enum VSMSGDEFS_METADATA {
    METADATA_NOT_SUPPORTED_ON_UNIX_RC = -4175,
    METADATA_CAN_NOT_CREATE_INSTANCE_RC = -4176,
    METADATA_CAN_NOT_CREATE_IMPORTER_RC = -4177,
};

#endif
