#ifndef VSMSGDEFS_SLKWAIT_H
#define VSMSGDEFS_SLKWAIT_H

enum VSMSGDEFS_SLKWAIT {
    SLKWAIT_HIT_ANY_KEY_RC = -3800,
    SLKWAIT_PRESS_ENTER_TO_CONTINUE_RC = -3801,
    SLKWAIT_JAVA_MESSAGE_RC = -3802,
};

#endif
