#ifndef VSMSGDEFS_UPCHECK_H
#define VSMSGDEFS_UPCHECK_H

enum VSMSGDEFS_UPCHECK {
    VSRC_UPCHECK_HELP = -9000,
    VSRC_UPCHECK_UNKNOWN_COMMAND = -9001,
    VSRC_UPCHECK_INVALID_ARGUMENT = -9002,
    VSRC_UPCHECK_ERROR_OPENING_OUTPUT_FILE = -9003,
    VSRC_UPCHECK_NOT_ENOUGH_ARGUMENTS = -9004,
    VSRC_UPCHECK_ACTION_FAILED = -9005,
    VSRC_UPCHECK_MISSING_ACTION_STATUS = -9006,
    VSRC_UPCHECK_NOT_FOUND = -9007,
    VSRC_UPCHECK_ERROR_STARTING = -9008,
    VSRC_UPCHECK_TIMED_OUT = -9009,
    VSRC_UPCHECK_INVALID_RESPONSE = -9010,
    VSRC_UPCHECK_VERSION_NOT_SUPPORTED = -9011,
    VSRC_UPCHECK_ERROR_CREATING_LOG = -9012,
    VSRC_UPCHECK_ERROR_SAVING_MANIFEST = -9013,
    VSRC_UPCHECK_ERROR_RETRIEVING_UPDATES = -9014,
    VSRC_UPCHECK_MANUAL_CHECK_HELP = -9015,
};

#endif
