#ifndef VSMSGDEFS_DELTASAVE_H
#define VSMSGDEFS_DELTASAVE_H

enum VSMSGDEFS_DELTASAVE {
    DS_COULD_NOT_CREATE_ARCHIVE_FILE_RC = -6900,
    DS_ARCHIVE_FILE_NOT_OPEN_RC = -6901,
    DS_SOURCE_FILENAME_NOT_SET_RC = -6902,
    DS_VERSION_NOT_FOUND_RC = -6903,
    DS_PRE_CALLBACK_FAILED_RC = -6904,
    DS_POST_CALLBACK_FAILED_RC = -6905,
    DS_FILE_MATCHED_RC = -6906,
    DS_NOT_CURRENT_BUFFER_RC = -6907,
    DS_COULD_NOT_OPEN_FILE_WITH_CODE_PAGE_RC = -6908,
    DS_FILE_EXCLUDED_RC = -6909,
};

#endif
