#ifndef VSMSGDEFS_SUNPAK_H
#define VSMSGDEFS_SUNPAK_H

enum VSMSGDEFS_SUNPAK {
    SUNPAK_INCORRECT_VERSION_RC = -480,
    SUNPAK_INVALID_COMPRESS_FILE_RC = -481,
    SUNPAK_ERROR_WRITING_FILE_RC = -482,
    SUNPAK_DECOMPRESSING_RC = -483,
    SUNPAK_DATE_NOT_SET_RC = -484,
    SUNPAK_ERROR_DATE_NOT_SET_RC = -485,
    SUNPAK_DATE_NOT_SET_UNIX_RC = -486,
    SUNPAK_ERROR_SETTING_PERMISSION_RC = -487,
    SUNPAK_INVALID_OPTION_RC = -488,
    SUNPAK_OPEN_ACCESS_DENIED_RC = -489,
};

#endif
