#ifndef VSMSGDEFS_VSSETLN_H
#define VSMSGDEFS_VSSETLN_H

enum VSMSGDEFS_VSSETLN {
    VSSETLN_UNABLE_TO_OPEN_FILE_RC = -300,
    VSSETLN_EXECUTABLE_FILE_NOT_FOUND_RC = -301,
    VSSETLN_ERROR_READING_FILE_RC = -302,
    VSSETLN_COULD_NOT_FIND_MARKER_RC = -303,
    VSSETLN_BAD_VERSION_NUMBER_RC = -304,
    VSSETLN_SERIAL_MARKER_NOT_FOUND_RC = -305,
    VSSETLN_ERROR_WRITING_TO_FILE_RC = -306,
    VSSETLN_LICENSE_STORED2_RC = -307,
    VSSETLN_LICENSE_STORED_RC = -308,
    VSSETLN_COPY_FAILED_RC = -309,
    VSSETLN_DELETE_FAILED_RC = -310,
    VSSETLN_MOVE_FAILED_RC = -311,
    VSSETLN_INVALID_KEY_RC = -312,
    VSSETLN_ENTER_FULL_PATH_RC = -313,
    VSSETLN_MUST_GIVE_PATH_AND_NAME_RC = -314,
    VSSETLN_PREFIX_MISMATCH_RC = -315,
    VSSETLN_VERSION_MISMATCH_RC = -316,
    VSSETLN_LOCATION_OF_EXE_RC = -317,
    VSSETLN_HELP_UNIX_RC = -318,
    VSSETLN_UNABLE_TO_EXECUTE_RC = -319,
    VSSETLN_LICENSE_MARKER_NOT_FOUND_RC = -320,
    VSSETLN_PACKS_MARKER_NOT_FOUND_RC = -321,
    VSSETLN_MESSAGEBOX_TITLE_RC = -322,
    VSSETLN_INVALID_KEY2_RC = -323,
    VSSETLNW_REPLACE_NOT_VALID_RC = -324,
    VSSETLN_REPLACE_NOT_VALID_RC = -325,
    VSSETLN_UNABLE_TO_UPDATE_LICENSE_FILE_RC = -326,
    VSSETLN_UNABLE_TO_OPEN_LICENSE_FILE_RC = -327,
    VSSETLN_SERIAL_AND_LICENSE_MISMATCH_RC = -328,
    VSSETLN_CANNOT_UPDATE_TRIAL_RC = -329,
    VSSETLN_NUMBER_OF_TIMES_PATCHED = -330,
};

#endif
