# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="afowler"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#

unsetopt NOMATCH

export LC_ALL=zh_TW.UTF-8
export LANG=zh_TW.UTF-8
export TERM=xterm
umask 022

alias sr='shutdown -r now'
alias sd='shutdown -h now'
alias ls='ls --color=always'
alias ll='ls -l --block-size=M'
alias less='less -r'
alias rm='rm -f'
alias h='history'
alias hc='history -c'
alias mnt='mount'
alias umnt='umount'
alias sx='startx'
alias lt='logout'
alias df='df -B G'
alias cl='clear'
alias vi='vim'
alias indent='indent  -bap -saf -sai -saw -npro -npcs -npsl -cli8 -i8 -ts8 -sob -l80 -ss -bl -bls -bli 0'
alias gcc='gcc -Wall -g -pedantic'
#alias indent='indent -npro -nip -nlp -npsl -i4 -ts4 -sob -l200 -ss -bl -bli 0 -l80'
alias style='astyle --style=kr --delete-empty-lines -s4 -K -f -p -H -U -c -n -N -L -Y -M -j -k1 -z2'

#HTC
#alias pull='adb pull /storage/sdcard0/htclog'
alias pull='adb pull /data/log'
alias tombstones='adb pull /data/tombstones'
alias dlx_envsetup='source build/envsetup.sh; choosecombo 1 dlx eng; export ANDROID_SOURCE=$(gettop)'
#alias m7dug_envsetup='source build/envsetup.sh; choosecombo 1 m7dug eng'
alias m7cdug_envsetup='source build/envsetup.sh ; partner_setup m7cdug M7CDUG_Generic_WWE_DEBUG ; partner_setup m7cdug M7CDUG_CU_CHS_DEBUG ;'
alias dlxp_envsetup='source build/envsetup.sh ; choosecombo 1 dlpdtu userdebug DEBUG'
alias a5tl_envsetup='source build/envsetup.sh ; partner_setup htc_a5tl A5TL_Generic_WWE_DEBUG'
alias sense60_envsetup='export HTCFW_ENABLED=true; source build/envsetup.sh ; partner_setup m7 M7_Generic_WWE_DEBUG'
alias img_zip='zip rom.zip -j android-info.txt *.img *.hdr'
alias logcat='adb logcat -c && adb logcat -v threadtime 2>&1 | tee /tmp/logcat.txt'
alias emulator_envsetup='source build/envsetup.sh; lunch full-eng'
#alias rm_log='adb shell rm /data/htclog/*'
alias eclipse='/home/shihyu/data/adt-bundle-linux-x86_64-20140702/eclipse/eclipse'
alias findcpp="find . -name '*.cpp' -print"
alias findc="find . -name '*.c'"
alias findh="find . -name '*.h'"
alias findmk="find . -name '*.mk'"
alias findjava="find . -name '*.java'"
alias netpid="netstat -tlnp"
#alias ag='ag -a'

HISTSIZE=10000
#PROMPT_COMMAND="history -a; history -n;"

kill_process()
{
    sudo kill -9  `ps aux | grep $1 | grep -v grep | awk '{print $2}'`
}

rm_log()
{
    adb shell rm /data/htclog/*;
    adb shell rm /data/log/*;
    adb shell rm /data/tombstones/tombstone_*;
}

#function dlx_envsetup()
#{
    #unset GREP_OPTIONS
 #   source build/envsetup.sh; choosecombo 1 dlx eng
    #export GREP_OPTIONS
#}

#export GREP_OPTIONS='--color=auto --binary-files=without-match --ignore-case'

alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."

alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

#alias gaia_zip="adb reboot-bootloader; flash_zip; fastboot reboot"

export HISTTIMEFORMAT='%F %T'
alias h1='history 10'
alias h2='history 20'
alias h3='history 30'

logsort()
{
    ls -lrt `find . -name "$1"` | awk '{print $NF}'
}

gaia_logparse()
{
    ack -w 'Exception|ANR|E\/|SIGSEGV|FATAL|EXCEPTION\:|W\/mutexwatch' $1 >  /tmp/aa ; vim /tmp/aa
}


get_maps()
{
    PID=`adb shell ps | grep $1 | awk '{print $2}'`
    adb shell cat /proc/$PID/maps > ~/maps
    sh /home/shihyu/gen_add_symbol_file.sh /home/shihyu/maps
}

attach_pid()
{
    PID=`adb shell ps | grep $1 | awk '{print $2}'`
    adb shell gdbserver :5039 --attach $PID
}

tar_bz2_dir()
{ # ©2007 dsplabs.com.au
    if [ "$1" != "" ]; then
        FOLDER_IN=`echo $1 |sed -e 's/\/$//'`;
        FILE_OUT="$FOLDER_IN.tar.bz2";
        FOLDER_IN="$FOLDER_IN/";
        echo "Compressing $FOLDER_IN into $FILE_OUT…";
        echo "tar cjf $FILE_OUT $FOLDER_IN";
        if [ -z "`apt-cache show pbzip2 2> /dev/null`" -o -z "pbzip2" ] ;
        then
            tar cjf "$FILE_OUT" "$FOLDER_IN";
        else
            time tar -c "$FOLDER_IN" | pbzip2 -cv -m5000 > "$FILE_OUT";
        fi
        echo "Done.";
    fi
}


d_bz2_dir()
{

    if [ "$1" != "" ]; then
        time pbzip2 -dvc -m5000 $1 | tar x
    fi
}

function gdbgaia()
{
    local SUDO="sudo env PATH=$PATH"
    local PS3="Choose the operating device:"
    local ADB="adb"
    local devices=($(${ADB} devices | awk '{if(FNR>1)print $1}'))
    local s=

    echo "${devices[@]}" | grep -q "\<$4\>" 2> /dev/null && devices=("$4")

    if [ ${#devices[@]} -eq 0 ]; then
        echo No devices
        return 2;
    elif [ ${#devices[@]} -gt 1 -a "$1" != "-a" ]; then
        select s in "${devices[@]}" "quit";
        do
            if [ -n "${s}" ]; then
                case "${s}" in
                "All devices")
                    break;
                    ;;
                "quit")
                    echo Quit!
                    return 1;
                    ;;
                *)
                    devices=(${s})
                    break;
                    ;;
                esac
            fi
        done
    fi

    local OUT_ROOT=$(get_abs_build_var PRODUCT_OUT)
    local OUT_SYMBOLS=$(get_abs_build_var TARGET_OUT_UNSTRIPPED)
    local OUT_SO_SYMBOLS=$(get_abs_build_var TARGET_OUT_SHARED_LIBRARIES_UNSTRIPPED)
    local OUT_EXE_SYMBOLS=$(get_abs_build_var TARGET_OUT_EXECUTABLES_UNSTRIPPED)
    local PREBUILTS=$(get_abs_build_var ANDROID_PREBUILTS)
    local ARCH=$(get_build_var TARGET_ARCH)
    local GDB
    case "$ARCH" in
        x86) GDB=i686-android-linux-gdb;;
        arm) GDB=arm-linux-androideabi-gdb;;
        *) echo "Unknown arch $ARCH"; return 1;;
    esac

    if [ "$OUT_ROOT" -a "$PREBUILTS" ]; then
        local EXE="$1"
        if [ "$EXE" ] ; then
            EXE=$1
        else
            EXE="app_process"
        fi

        local PORT="$2"
        if [ "$PORT" ] ; then
            PORT=$2
        else
            PORT=":5039"
        fi

        local PID
        local PROG="$3"
        if [ "$PROG" ] ; then
            if [[ "$PROG" =~ ^[0-9]+$ ]] ; then
                PID="$3"
            else
                PID=`pid $3 ${devices[0]}`
            fi
            if [ -n "${devices[0]}" ]; then
                adb -s ${devices[0]} forward "tcp$PORT" "tcp$PORT"
                adb -s ${devices[0]} shell gdbserver $PORT --attach $PID &
            else
                adb forward "tcp$PORT" "tcp$PORT"
                adb shell gdbserver $PORT --attach $PID &
            fi
            sleep 2
        else
                echo ""
                echo "If you haven't done so already, do this first on the device:"
                echo "    gdbserver $PORT /system/bin/$EXE"
                    echo " or"
                echo "    gdbserver $PORT --attach $PID"
                echo ""
        fi

        echo >|"$OUT_ROOT/gdbclient.cmds" "set solib-absolute-prefix $OUT_SYMBOLS"
        echo >>"$OUT_ROOT/gdbclient.cmds" "set solib-search-path $OUT_SO_SYMBOLS:$OUT_SO_SYMBOLS/hw:$OUT_SO_SYMBOLS/ssl/engines"
        echo >>"$OUT_ROOT/gdbclient.cmds" "set watchdog 200000000"
        echo >>"$OUT_ROOT/gdbclient.cmds" "target remote $PORT"
        echo >>"$OUT_ROOT/gdbclient.cmds" ""

        $ANDROID_TOOLCHAIN/$GDB -x "$ANDROID_SOURCE/Mygdbinit" -x "$OUT_ROOT/gdbclient.cmds" "$OUT_EXE_SYMBOLS/$EXE"
        #$ANDROID_TOOLCHAIN/$GDB -x "$ANDROID_SOURCE/Mygdbinit"  "$OUT_EXE_SYMBOLS/$EXE"
    else
        echo "Unable to determine build system output dir."
    fi
}

function mkdircd () { mkdir -p "$@" && eval cd "\"\$$#\""; }

push_so()
{
    adb shell rm /data/log/* ;
    adb shell rm /data/memleak/* ;
    adb shell rm /data/tombstones/tomb* ;
    adb remount ;
    adb push $1 /system/lib ;
    adb reboot
}

gaia_lib()
{
    time make $1 ONLYSDKAP=true -j8 2>&1 |tee build.log
}

gaia_mm()
{
    time mm ONLYSDKAP=true -j8 2>&1 |tee build.log
}

gaia_sync()
{
    #adb shell rm /data/log/* &&
    rm_log &&
    adb remount &&
    adb sync &&
    adb reboot
}

push_apk()
{
    adb shell rm /data/log/* ;
    adb remount ;
    adb push $1 /system/app ;
    adb reboot
}

tar_bz2_dir()
{ # ©2007 dsplabs.com.au
    if [ "$1" != "" ]; then
        FOLDER_IN=`echo $1 |sed -e 's/\/$//'`;
        FILE_OUT="$FOLDER_IN.tar.bz2";
        FOLDER_IN="$FOLDER_IN/";
        echo "Compressing $FOLDER_IN into $FILE_OUT…";
        echo "tar cjf $FILE_OUT $FOLDER_IN";
        if [ -z "`apt-cache show pbzip2 2> /dev/null`" -o -z "pbzip2" ] ;
        then
            tar cjf "$FILE_OUT" "$FOLDER_IN";
        else
            time tar -c "$FOLDER_IN" | pbzip2 -c > "$FILE_OUT";
        fi
        echo "Done.";
    fi
}

attach_pid()
{
    PID=`adb shell ps | grep $1 | awk '{print $2}'`
    adb shell gdbserver :5039 --attach $PID
}

get_maps()
{
    PID=`adb shell ps | grep $1 | awk '{print $2}'`
    adb shell cat /proc/$PID/maps > ~/maps
    sh /home/shihyu/gen_add_symbol_file.sh /home/shihyu/maps
}

d_bz2_dir()
{
    if [ "$1" != "" ]; then
        time pbzip2 -dvc -m5000 $1 | tar x
    fi
}

scopy()
{
    scp $1 shihyu@$2:~/upload
}

function htc_flash_zip()
{
    local OUT_ROOT=$(get_abs_build_var PRODUCT_OUT)
    local file_name=( $(md5sum $OUT_ROOT/boot.img) )
    file_name="$PWD/${file_name[0]}.zip"

    local flash_cmd="sudo $HOME/.bin/htc_fastboot flash zip $file_name"

    echo "Product: $TARGET_PRODUCT"
    echo "Zipping file for fastbooting..."
    sudo echo -n
    zip -j $file_name $OUT_ROOT/{*.img,*.hdr,android-info.txt}

    eval $flash_cmd $* || eval $flash_cmd $*
}

gaia_zip()
{
    adb reboot-bootloader

    #htc_flash_zip
    flash_zip

    while [ $? = 1 ]; do
        sleep 3
        #htc_flash_zip
        flash_zip
    done

    htc_fastboot reboot
}

gaia_rom()
{
    adb reboot-bootloader
    #if [ "`zip -sf $1 | grep qsc_radio.img`" != "" ]; then
        #zip $1 -d qsc_radio.img
    #fi
    echo "partial rom start"
    fastboot flash zip $1
    while [ $? = 1 ]; do
        sleep 3
        fastboot flash zip $1
    done
    echo "partial rom end"
    fastboot reboot-bootloader
    echo "COS rom start"
    fastboot flash zip $2
    while [ $? = 1 ]; do
        sleep 3
        fastboot flash zip $2
    done
    echo "COS rom end"
    fastboot reboot
}

htc_fastboot_rom()
{
    adb reboot-bootloader
    #if [ "`zip -sf $1 | grep qsc_radio.img`" != "" ]; then
        #zip $1 -d qsc_radio.img
    #fi
    echo "partial rom start"
    $HOME/.bin/htc_fastboot flash zip $1
    while [ $? = 1 ]; do
        sleep 3
        $HOME/.bin/htc_fastboot flash zip $1
    done
    echo "partial rom end"
    fastboot reboot-bootloader
    echo "COS rom start"
    $HOME/.bin/htc_fastboot flash zip $2
    while [ $? = 1 ]; do
        sleep 3
        $HOME/.bin/htc_fastboot flash zip $2
    done
    echo "COS rom end"
    fastboot reboot
}

gaia_logparse()
{
   ack -w 'Exception|ANR|E\/|SIGSEGV|FATAL|EXCEPTION\:|W\/mutexwatch|die|>>> .* <<<|permission|Out of memory|Call stack\:|#[\d][\d]' $1 >  /tmp/aa ; vim /tmp/aa
}

logack()
{
    ls -rt | find . -name "$1" | xargs ack -Q "$2"
}

# colorful man page
export PAGER="`which less` -s"
export BROWSER="$PAGER"
export LESS_TERMCAP_mb=$'\E[38;5;167m'
export LESS_TERMCAP_md=$'\E[38;5;39m'
export LESS_TERMCAP_me=$'\E[38;5;231m'
export LESS_TERMCAP_se=$'\E[38;5;231m'
export LESS_TERMCAP_so=$'\E[38;5;167m'
export LESS_TERMCAP_ue=$'\E[38;5;231m'
export LESS_TERMCAP_us=$'\E[38;5;167m'





export AUTOSSH_DEBUG=DEBUG
export AUTOSSH_LOGFILE=~/.autohssh.log

CD()
{
    if [ -f "$1" ]; then
        cd `dirname "$1"`
    else
        cd $1
    fi
}



export PATH=$HOME/.mybin:$PATH
eval "$(fasd --init auto)"

export PATH=$HOME/.mybin/meld-3.12.0/bin:$PATH

#boost
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/boost/include
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/boost/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/boost/lib


export PATH="/home/shihyu/data/tq210_note/4.4.6/bin/:$PATH"
export PATH="/home/shihyu/data/tq210_note/mkimage/:$PATH"
export PATH="/usr/local/gdb-7.8/bin:$PATH"


export PATH="/usr/local/qemu-linaro/bin:$PATH"



JAVA_HOME=/media/shihyu/Toshiba/jdk1.6.0_45
export JRE_HOME=$JAVA_HOME/jre  
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH    
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH 

export PATH="/home/shihyu/Bin/LiveSuit/bin:$PATH"

export PATH="/home/shihyu/data/bluegriffon:$PATH"

export PATH="/home/shihyu/.mybin/scitools/bin/linux64:$PATH"

export PATH=/home/shihyu/Qt5.3.1/5.3/gcc_64/bin:$PATH

export PATH=/usr/local/node-v0.10.31-linux-x64/bin:$PATH


PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opencv/lib/pkgconfig
export PKG_CONFIG_PATH

ulimit -c unlimited


