#!/bin/bash
#Name: pcpu_usage.sh
#Description: Script to calculate cpu usage by processes for 1 hour

SECS=3600
#Change the SECS to custom seconds

STEPS=$(( $SECS / 60 ))

echo Watching CPU usage... ;

logfile=/tmp/cpu_usage.$

for((i=0;i<STEPS;i++))
do
    ps -eo comm,pcpu,pid | sort -k2nr |head -30 >> $logfile
    sleep 60
done

echo
echo CPU eaters :

awk '{ process[$1 FS $3]+=$2; }
    END{ for(i in process) print i, process[i] }' $logfile | sort -k2nr | head | cut -d" " -f1 
