// generated by 'generate-g++-header.sh hpux'

// output of 'cpp -dM'
#define hppa 1
#define hpux 1
#define __HAVE_BUILTIN_SETJMP__ 1
#define __hp9000s800__ 1
#define __unix__ 1
#define unix 1
#define __SIZE_TYPE__ long unsigned int
#define __hppa 1
#define __hpux 1
#define __hp9000s700 1
#define __PWB__ 1
#define __unix 1
#define __hp9k8__ 1
#define hp9000s800 1
#define __USER_LABEL_PREFIX__ 
#define __STDC_HOSTED__ 1
#define __PWB 1
#define __WCHAR_TYPE__ unsigned int
#define _PA_RISC1_1 1
#define __WINT_TYPE__ unsigned int
#define PWB 1
#define __USING_SJLJ_EXCEPTIONS__ 1
#define __hppa__ 1
#define __hp9k8 1
#define __hp9000s800 1
#define hp9k8 1
#define _INCLUDE_LONGLONG 1
#define __STDC__ 1
#define __PTRDIFF_TYPE__ long int
#define __hpux__ 1
#define _HIUX_SOURCE 1
#define __REGISTER_PREFIX__ 
#define _HPUX_SOURCE 1
#define __NO_INLINE__ 1
#define __STDC_EXT__ 1
#define __VERSION__ "3.2.2"

// include common header
#include "g++-common.h"

