// generated by 'generate-g++-header.sh sgi'

// output of 'cpp -dM'
#define __DBL_MIN_EXP__ (-1021)
#define sgi 1
#define __EXTENSIONS__ 1
#define __FLT_MIN__ 1.17549435e-38F
#define _MIPS_TUNE_MIPS3 1
#define _COMPILER_VERSION 601
#define __CHAR_BIT__ 8
#define __SYSTYPE_SVR4__ 1
#define __WCHAR_MAX__ 2147483647
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __FLT_EVAL_METHOD__ 0
#define __unix__ 1
#define unix 1
#define __SIZE_TYPE__ unsigned int
#define __SYSTYPE_SVR4 1
#define _MIPS_ISA _MIPS_ISA_MIPS3
#define SYSTYPE_SVR4 1
#define __LANGUAGE_C 1
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define _MIPS_TUNE "mips3"
#define __FLT_RADIX__ 2
#define __LDBL_EPSILON__ 2.46519032881566189191165176650871e-32L
#define __mips64 1
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.79769313486231590772930519078900e+308L
#define __DSO__ 1
#define host_mips 1
#define __LANGUAGE_C__ 1
#define __host_mips 1
#define __CHAR_UNSIGNED__ 1
#define _MIPS_SZPTR 32
#define __LDBL_MAX_EXP__ 1024
#define _MODERN_C 1
#define _R4000 1
#define __LONG_MAX__ 2147483647L
#define __unix 1
#define __SCHAR_MAX__ 127
#define __DBL_DIG__ 15
#define _mips 1
#define __USER_LABEL_PREFIX__ 
#define __STDC_HOSTED__ 1
#define _MIPS_SZINT 32
#define __mips_fpr 64
#define __LDBL_MANT_DIG__ 106
#define __FLT_EPSILON__ 1.19209290e-7F
#define _LONGLONG 1
#define __MIPSEB 1
#define __LDBL_MIN__ 2.00416836000897277799610805135016e-292L
#define __WCHAR_TYPE__ long int
#define MIPSEB 1
#define __host_mips__ 1
#define __FLT_DIG__ 6
#define __FLT_MAX_10_EXP__ 38
#define __INT_MAX__ 2147483647
#define __FLT_MAX_EXP__ 128
#define _MIPS_SIM _ABIN32
#define __DECIMAL_DIG__ 33
#define __DBL_MANT_DIG__ 53
#define __mips__ 1
#define __WINT_TYPE__ long int
#define __LDBL_MIN_EXP__ (-968)
#define _MIPS_FPSET 32
#define __LDBL_MAX_10_EXP__ 308
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define _SGI_SOURCE 1
#define __DBL_MAX__ 1.7976931348623157e+308
#define _ABIN32 2
#define __R4000 1
#define __DBL_MAX_EXP__ 1024
#define mips 1
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __sgi 1
#define _MIPS_ARCH_MIPS3 1
#define __FLT_MAX__ 3.40282347e+38F
#define LANGUAGE_C 1
#define R4000 1
#define __GXX_ABI_VERSION 102
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MIN_EXP__ (-125)
#define _LANGUAGE_C 1
#define __MIPSEB__ 1
#define __DBL_MAX_10_EXP__ 308
#define _MIPSEB 1
#define __LDBL_DENORM_MIN__ 4.94065645841246544176568792868221e-324L
#define __DBL_MIN__ 2.2250738585072014e-308
#define _MIPS_ARCH "mips3"
#define _SVR4_SOURCE 1
#define __mips_hard_float 1
#define __PTRDIFF_TYPE__ int
#define __mips 3
#define __sgi__ 1
#define _MIPS_SZLONG 32
#define __R4000__ 1
#define __LDBL_MIN_10_EXP__ (-291)
#define __REGISTER_PREFIX__ 
#define __LDBL_DIG__ 31
#define __NO_INLINE__ 1
#define __FLT_MANT_DIG__ 24
#define __VERSION__ "3.3.2"

// include common header
#include "g++-common.h"

