#!/bin/sh

if [ "$1" = "" ] 
then
    echo "usage: generate-g++-header.sh platform"
    exit 2
fi

f="g++-"$1".h"

echo "// generated by 'generate-g++-header.sh $1'" > $f
echo "" >> $f
echo "// output of 'cpp -dM'" >> $f
echo "" | cpp -dM >> $f
echo "" >> $f
echo "// include common header" >> $f
echo "#include \"g++-common.h\"" >> $f
echo "" >> $f

echo "created:  $f"
