#pragma once

enum CMERROR_TAGSDB {
    CMRC_TAGSDB_INVALID_DATABASE_TAGSDB_DATABASE_MARKER_MISSING = -103899,
    CMRC_TAGSDB_VERSION_NOT_SUPPORTED = -103898,
    CMRC_TAGSDB_TABLE_OR_INDEX_MISSING = -103897,
    CMRCEND_TAGSDB = -103900,
};
