#pragma once

enum VSMSGDEFS_VSMFUNDO {
    VSRC_MFUNDO_STACK_EMPTY = -7200,
    VSRC_MFUNDO_STEP_ALREADY_ENDED = -7201,
    VSRC_MFUNDO_END_STEP_NOT_CALLED = -7202,
    VSRC_FAILED_TO_GENERATE_REDO_INFO = -7203,
    VSRC_MFUNDO_BEGIN_NOT_CALLED = -7204,
    VSRC_MFUNDO_BEGIN_STEP_NOT_CALLED = -7205,
};
