#pragma once

enum VSMSGDEFS_VSDIFF {
    VSDIFF_USAGE_RC = -7000,
    VSDIFF_FILE_NOT_FOUND_RC = -7001,
    VSDIFF_NO_MORE_DIFFERENCES_RC = -7002,
    VSDIFF_NO_MORE_CONFLICTS_RC = -7003,
    VSDIFF_APP_NAME = -7004,
    VSDIFF_NO_MORE_DIFFERENCES_CLOSE_RC = -7005,
    VSDIFF_TIMED_OUT_RC = -7006,
    VSDIFF_LINE_TOO_LONG_RC = -7007,
    VSDIFF_ERROR_HASHING_FILES_RC = -7008,
    VSDIFF_NOT_INTIALIZED = -7009,
    VSDIFF_BACKGROUND_DIFF_ALREADY_RUNNING = -7010,
};
