#pragma once

enum VSMSGDEFS_FTP {
    VSRC_FTP_BAD_RESPONSE = -6851,
    VSRC_FTP_CONNECTION_DEAD = -6852,
    VSRC_FTP_CANNOT_STAT = -6853,
    VSRC_FTP_WAITING_FOR_REPLY = -6854,
    VSRC_FTP_BAD_CONFIG = -6855,
    VSRC_FTP_CANNOT_AUTHENTICATE = -6856,
    VSRC_FTP_END_ERRORS = -6899,
};
