#pragma once

enum VSMSGDEFS_LISTVTG {
    LISTVTG_VERSION_RC = -600,
    LISTVTG_INVALID_FILENAME_RC = -601,
    LISTVTG_DBOPEN_ERROR_RC = -602,
    LISTVTG_LISTING_DBFILE_RC = -603,
    LISTVTG_SEEK_LOC_CAPTION_RC = -604,
    LISTVTG_FILE_CAPTION_RC = -605,
    LISTVTG_DATE_CAPTION_RC = -606,
    LISTVTG_PACKAGE_CLASS_CAPTION_RC = -607,
    LISTVTG_PARENTS_CAPTION_RC = -608,
    LISTVTG_TAG_RC = -609,
    LISTVTG_CLASS_CAPTION_RC = -610,
    LISTVTG_FLAGSTYPE_CAPTION_RC = -611,
    LISTVTG_FILELINE_CAPTION_RC = -612,
    LISTVTG_ERROR_CLOSING_DATABASE_RC = -613,
    LISTVTG_FINISHED_RC = -614,
    LISTVTG_EXTN_CAPTION_RC = -615,
    LISTVTG_OCCURRENCE_RC = -616,
    LISTVTG_FILESEEKPOS_CAPTION_RC = -617,
};
