#pragma once

enum VSMSGDEFS_BSC {
    BSC_INCORRECT_EXTENSION_RC = -4160,
    BSC_ERROR_OPENING_FILE_RC = -4161,
    BSC_NO_INSTANCES_RC = -4162,
    BSC_ONLY_ON_WINDOWS_RC = -4163,
    BSC_CANNOT_OPEN_DLL_RC = -4164,
};
