#pragma once

enum VSMSGDEFS_SUBVERSION {
    SVN_COMMAND_RETURNED_ERROR_RC = -6650,
    SVN_DIRECTORIES_NOT_SUPPORTED_RC = -6651,
    SVN_FILE_NOT_CONTROLLED_RC = -6652,
    SVN_APP_NAME_RC = -6653,
    SVN_COULD_NOT_GET_LOG_INFO_RC = -6654,
    SVN_ERROR_CHECKOUT_FAILED_RC = -6655,
    SVN_ERROR_CANT_GET_PASSWORD = -6656,
    SVN_OUTPUT_TOO_LARGE = -6657,
    SVN_COMMAND_RETURNED_ERROR_FOR_PATH_RC = -6658,
};
