#pragma once

enum VSMSGDEFS_VSEXECFROMFILE {
    RCVSEXECFROMFILE_USAGE = -4500,
    RCVSEXECFROMFILE_UNABLE_TO_OPEN_FILE = -4501,
    RCVSEXECFROMFILE_ERROR_READING_COMMAND_LINE = -4502,
    RCVSEXECFROMFILE_EXECUTING = -4503,
    RCVSEXECFROMFILE_ARGUMENT_LIST_TOO_BIG = -4504,
    RCVSEXECFROMFILE_INVALID_EXECUTABLE = -4505,
    RCVSEXECFROMFILE_COMMAND_INTERPRETER_NOT_FOUND = -4506,
    RCVSEXECFROMFILE_PROGRAM_NOT_FOUND = -4507,
    RCVSEXECFROMFILE_NOT_ENOUGH_MEMORY = -4508,
    RCVSEXECFROMFILE_ERROR_EXECUTING_COMMAND = -4509,
};
