#pragma once

enum VSMSGDEFS_SLKSHELL {
    SLKSHELL_HELP_RC = -3750,
    SLKSHELL_PROGRAM_NOT_FOUND_RC = -3752,
    SLKSHELL_COMSPEC_MUST_BE_SET_RC = -3753,
    SLKSHELL_INVALID_DIRECTORY_RC = -3754,
    SLKSHELL_SYNTAX_INCORRECT_RC = -3755,
};
