#pragma once

enum VSMSGDEFS_JAVA {
    JAVA_CLASS_INCOMPLETE_HEADER_RC = -4170,
    JAVA_CLASS_BAD_MAGIC_NUMBER_RC = -4171,
    JAVA_CLASS_UNSUPPORTED_VERSION_RC = -4172,
    JAVA_CLASS_UNKNOWN_CONSTANT_TYPE_RC = -4173,
    JAVA_CLASS_ATTRIBUTE_LENGTH_MISMATCH_RC = -4174,
    JAVA_CLASS_SOURCE_NOT_FOUND_RC = -4175,
    JAVA_CLASS_INVALID_CONSTANT_INDEX_RC = -4176,
    JAVA_CLASS_STRING_NOT_FOUND_RC = -4177,
    JAVA_JAR_INCOMPLETE_HEADER_RC = -4178,
    JAVA_JAR_BAD_MAGIC_NUMBER_RC = -4179,
    JAVA_JAR_UNSUPPORTED_VERSION_RC = -4180,
    JAVA_JAR_DECOMPRESS_ERROR_RC = -4181,
    JAVA_JAR_CORRUPT_HEADER_RC = -4182,
};
