#pragma once

enum VSMSGDEFS_OBJECT {
    OBJECT_FILE_INCOMPLETE_HEADER_RC = -4185,
    OBJECT_FILE_BAD_MAGIC_NUMBER_RC = -4186,
    OBJECT_FILE_UNRECOGNIZED_RC = -4187,
    OBJECT_FILE_NO_DEBUG_RC = -4188,
};
