#pragma once

enum VSMSGDEFS_DELTASAVE {
    DS_COULD_NOT_CREATE_ARCHIVE_FILE_RC = -6900,
    DS_ARCHIVE_FILE_NOT_OPEN_RC = -6901,
    DS_SOURCE_FILENAME_NOT_SET_RC = -6902,
    DS_VERSION_NOT_FOUND_RC = -6903,
    DS_PRE_CALLBACK_FAILED_RC = -6904,
    DS_POST_CALLBACK_FAILED_RC = -6905,
    DS_FILE_MATCHED_RC = -6906,
    DS_NOT_CURRENT_BUFFER_RC = -6907,
    DS_COULD_NOT_OPEN_FILE_WITH_CODE_PAGE_RC = -6908,
    DS_FILE_EXCLUDED_RC = -6909,
    DS_COULD_NOT_FIND_VERSION_RC = -6910,
    DS_SOURCE_FILENAMNE_NOT_SET = -6911,
    DS_CANNOT_BACKUP_THIS_FILE_RC = -6912,
    DS_CANNOT_REPLACE_MOST_RECENT_FILE_RC = -6913,
    DS_CANNOT_LOAD_BACKUP_MOST_RECENT_FILE_RC = -6914,
    DS_CANNOT_CREATE_BACKUP_FOR_FILE_RC = -6915,
    DS_INVALID_CHECKSUM_RC = -6916,
    DS_COULD_NOT_READ_ARCHIVE_FILE_RC = -6917,
    DS_VERSION_DOES_NOT_HAVE_CHECKSUM_RC = -6918,
};
